### ISSUE TITLE
`:WakaTimeToday` still uses python

### ISSUE THREAD

**Issue by felipeqq2** [wakatime/vim-wakatime#101]
Apparently, this plugin no longer depends on Python (c8e32692b630975dc1edd1c4f6ceb5ae67a42083). However, when running `:WakaTimeToday` it complains about it:
```
Today: fish: Unknown command: python
fish:
'python' '-W' 'ignore' '/nix/store/xzhjwzfpm1nrv6ahi9hhswnly5iqjhm7-vimplugin-vim-wakatime-2021-09-27/packages/wakatime/
cli.py' '--today'
^
Press ENTER or type command to continue
```

I'm using Neovim v0.5.1

**Comment by alanhamlett** [comment]
You're using the latest vim-wakatime? That error message shouldn't be possible with the latest plugin version.

**Comment by felipeqq2** [comment]
Ha, I thought the last version was v8 (I'm using a59c321ed5043ccbd47b3d00185890fa13035ce3). Thanks!
