### ISSUE TITLE
Plugin root folder forced as OSX on linux

### ISSUE THREAD

**Issue by Mte90** [wakatime/vim-wakatime#103]
![immagine](https://user-images.githubusercontent.com/403283/140049710-44db8089-de63-4987-8073-ed891b94016c.png)

This is the error I am getting that this path is wrong as I am on linux and `/Users/` doesn't exist.
Looking at the code https://github.com/wakatime/vim-wakatime/blob/e7411f2491f2a8a653ddd46de60af6ff7f36cbbe/plugin/wakatime.vim#L46 seems that the line need to be inverted.

**Comment by oiwn** [comment]
It's same on OSX

IDK why this path is hardcoded

```/Library/Developer/CommandLineTools/usr/bin/python3: can't open file '/Users/user/git/vim-wakatime/scripts/install_cli.py'```

**Comment by Mte90** [comment]
I guess something left on debugging and committed.

**Comment by alanhamlett** [comment]
Fixed with d808ca0b4764379168b677a5cf6275d6484b6445.
