### ISSUE TITLE
Failing to detect python as a language

### ISSUE THREAD

**Issue by andrehgdias** [wakatime/vim-wakatime#111]
The plugin is detecting "ON" as a language instead of python.

Running Neovim v0.6.0-dev+566-g4174244d8 with [Lunarvim](https://github.com/LunarVim/LunarVim)

**Comment by alanhamlett** [comment]
Could you share the contents of one file that's being detected incorrectly?

**Comment by andrehgdias** [comment]
It happens for every python project I work on. At first, I thought it was because my projects were on my external hard drive, but today I tested at a local file and the same thing happens...
It also fails to recognize my project name based on its folder, so I'm always starting a local git repo so it's correctly recognized.

**Comment by alanhamlett** [comment]
> It happens for every python project I work on. At first, I thought it was because my projects were on my external hard drive, but today I tested at a local file and the same thing happens... 

Can you run this command and point it to one of your Python files having the issue, then let me know the output?

```bash
~/.wakatime/wakatime-cli-* --verbose --log-to-stdout --entity <path-to-your-py-file>
```

> It also fails to recognize my project name based on its folder, so I'm always starting a local git repo so it's correctly recognized.

The plugin requires a Git repo to detect the project, so it's normal that it won't be able to detect your project without knowing it's top-level folder:
https://wakatime.com/faq#create-projects

**Comment by andrehgdias** [comment]
Sorry for the delay:
https://codeshare.io/G6QnRp

**Comment by alanhamlett** [comment]
That log shows `"language":"Python"` is being sent to the API, so sometimes it's working and detecting `Python` but other times it's detecting `ON`. Can you share the contents of that `main.py` file so I can test locally?

**Comment by KalleChen** [comment]
Hi, @alanhamlett I had the same problem with Neovim v0.6.0-dev+565-g8cbe100fc with Lunarvim. But it can't also detect js, json, CSS file.
<img width="853" alt="Screen Shot 2021-12-02 at 11 10 15 AM" src="https://user-images.githubusercontent.com/48475056/144350863-0f0f60b9-5800-4be7-8c72-f75724e478c8.png">
Here are my logs.
![Screen Shot 2021-12-02 at 11 13 45 AM](https://user-images.githubusercontent.com/48475056/144351233-ef498f5f-e17d-4cfd-8dc7-e4a76d168435.png)

And the code.
![Screen Shot 2021-12-02 at 11 14 10 AM](https://user-images.githubusercontent.com/48475056/144351280-4ac893b3-bbf8-408f-a16a-e6d2c328fb29.png)

**Comment by alanhamlett** [comment]
With `main-page-mobile.js` open inside NeoVim what's the output from these two commands?

`:echo &syntax`

`:echo &filetype`

**Comment by KalleChen** [comment]
&syntax -> ON
&filetype -> javascript

**Comment by alanhamlett** [comment]
Can you see if the latest vim-wakatime plugin update fixes it for you?

**Comment by KalleChen** [comment]
It didn't work. Still got ON and &syntax is still ON after updating. 🥲

**Comment by alanhamlett** [comment]
You'll still get &syntax ON but the plugin stopped using it as language unless it couldn't detect the language on its own.

**Comment by KalleChen** [comment]
Oh got it. I thought that &syntax should be the same with filetype after updating. I think it works for me now, it can detect js or py files. Thanks for helping.😄
