### ISSUE TITLE
At every nvim boot the UI is blocked for updates

### ISSUE THREAD

**Issue by Mte90** [wakatime/vim-wakatime#113]
As:
![immagine](https://user-images.githubusercontent.com/403283/145014265-82af7a7c-2961-45ef-9eb2-488f4f850342.png)

I get this at every nvim boot so I have to press esc to move on otherwise enter that will print any step of the update process.
It is very annoying.

**Comment by alanhamlett** [comment]
Turn off debug mode and it will stop printing these debug messages:

`:WakaTimeDebugDisable`
