### ISSUE TITLE
Neovim on Windows 10: Download wakatime-cli and extract into the ~/.wakatime/ folder

### ISSUE THREAD

**Issue by erwin** [wakatime/vim-wakatime#114]
On Windows 10 Neovim 0.6 I'm getting a warning each time I launch neovim.

```
Download wakatime-cli and extract into the ~/.wakatime/ folder:
https://github.com/wakatime/wakatime-cli/releases/latest/download/wakatime-cli-windows-amd64.zip
Press ENTER or type command to continue
```

Yet I have repeated the procedure here described many times, but each time I still get the same error/warning.

```
C:\Users\erwin\.wakatime>echo %HOMEPATH%
\Users\erwin

C:\Users\erwin\.wakatime>ls -l
total 49140
-rwxr-xr-x 1 erwin Administrators 16773120 Dec  2 22:21 wakatime-cli-windows-amd64.exe
```

I can run `wakatime --today` and it works fine...

```
C:\Users\erwin>wakatime-cli-windows-amd64 --today
1 hr 2 mins
```

I read the source for the plugin and it doesn't make sense to me why it's not finding the file..

I was able to work around in `init.lua` by setting:

```
if os.getenv("TERM") == "vtpcon" then
  vim.g.wakatime_CLIPath = os.getenv("HOMEPATH")  .. "/.wakatime/wakatime-cli-windows-amd64.exe"
end
```

(I share the same config on all machines, so I check TERM == vtpcon to know it's running under the windows `cmd.exe` shell. Whether running under the old school conhost or the newer Windows Terminal app, TERM will still be set to `vtpcon` when running under cmd.exe.

**Comment by alanhamlett** [comment]
Fixed if you update to the latest version of the plugin.
