### ISSUE TITLE
Latest commit breaks vim

### ISSUE THREAD

**Issue by queensferryme** [wakatime/vim-wakatime#118]
d192f6014f5979411a54c3ae60a9fcd88f5afe7d
Giving me this error:
![图片](https://user-images.githubusercontent.com/41495669/147387505-fe4109e8-4421-4037-9e0e-e9c7350fc419.png)

**Comment by queensferryme** [comment]
Hey, I think I've found the issue. PTAL @alanhamlett

**Comment by williamboman** [comment]
I'm experiencing this as well! #119 seems to fix it :+1:
