### ISSUE TITLE
Symlink require administrator on Windows

### ISSUE THREAD

**Issue by moeshin** [wakatime/vim-wakatime#122]
We can:
* Require administrator
* Download directly as `~/.wakatime/wakatime-cli`
* https://github.com/wakatime/vim-wakatime/blob/7a6d776a6a36d432cad3ef1e7c926f6d777e57bc/scripts/install_cli.py#L59-L64 Handle exceptions by copying file
* ...

**Comment by moeshin** [comment]
And the suffix of the executable file require be `.exe`  in nvim.
```text
E903: Process failed to start: no such file or directory
```

**Comment by alanhamlett** [comment]
If you copy the file to `~/.wakatime/wakatime-cli` (without `.exe`) does it work? We can have the install script do the same on Windows.

**Comment by moeshin** [comment]
vim work, nvim no work:
```text
E903: Process failed to start: no such file or directory: "C:/Users/MoeShin/.wakatime/wakatime-cli"
```

**Comment by moeshin** [comment]
They can all work with `.exe`.

https://github.com/wakatime/vim-wakatime/blob/7a6d776a6a36d432cad3ef1e7c926f6d777e57bc/scripts/install_cli.py#L59
```python
if is_win:
    link += '.exe'
```

**Comment by alanhamlett** [comment]
How about now, with 3bdb70ef3a691d3017459a351547736b08398a41?

**Comment by moeshin** [comment]
nvim no run install_cli.py

**Comment by moeshin** [comment]
> nvim no run install_cli.py

#123

**Comment by alanhamlett** [comment]
What's your output when you run this in Vim and Nvim?

`:echo &shell`

**Comment by moeshin** [comment]
In vim (MSYS2)
```vim
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" -c
```

In nvim (MSYS2)
```vim
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" /s /c
```
--------
In vim (CMD)
```vim
echo &shell
" C:\WINDOWS\system32\cmd.exe

echo &shellcmdflag
" /c
```

In nvim (CMD)
```vim
echo &shell
" cmd.exe

echo &shellcmdflag
" /s /c
```

**Comment by alanhamlett** [comment]
I just pushed 55d42cf57722178eeafc53f225ec5e097e391652. Can you update and see if it fixes things for you on Vim and Nvim?

**Comment by alanhamlett** [comment]
Also, thanks for `&shellcmdflag` I had forgotten to ask for that output too!

**Comment by moeshin** [comment]
In MSYS2
```text
[WakaTime] 127: /usr/bin/zsh: can't open input file: /s /c
```
```vim 
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" /s /c
```

**Comment by alanhamlett** [comment]
How about now after debf1efd7b1a247470f5f390c6d1003644fa9988? Thanks for helping debug this!

**Comment by moeshin** [comment]
in MSYS2 only nvim
```text
[WakaTime] 127: /usr/bin/zsh: can't open input file: /s
```
in CMD
```text
[WakaTime] 2: /usr/bin/python3: can't open file '/c/Users/MoeShin/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py': [Errno 2] No such file or directory
```
-------
By the way，I python3 install by pacman on MSYS2.

**Comment by alanhamlett** [comment]
Some cleanup with 49591edc4c39b329dd9eb7490e6590c57bd6c016 so now Vim and NVim both use the same command. Maybe this will help simplify debugging. Can you update and try it out?

**Comment by moeshin** [comment]
no change

**Comment by alanhamlett** [comment]
If you revert `plugin/wakatime.vim` back to the state it was in from your PR #123 (1d878453cca7044b1d774e8fd51763c524eb909d) I'm curious does it work in all variants Vim/NVim/CMD/MSYS2?

**Comment by moeshin** [comment]
No, it has bug.
I have rolled back and modified https://github.com/moeshin/vim-wakatime/commit/3e54260bae8d7b754cadb043170057a635e052bd

**Comment by moeshin** [comment]
The problem is in python.
Python3 installed by pacman in MSYS2, the script path require unix style.
```
[WakaTime] 2: /usr/bin/python3: can't open file '/c/Users/MoeShin/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py': [Errno 2] No such file or directory
```

**Comment by alanhamlett** [comment]
So the path for `install_cli.py` that works in MSYS2 is this?
`//c/Users/MoeShin/C//Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py`

After `let install_script = '/' . substitute(install_script, ':', '/', '')`. Is the double slash at start necessary or does it work with a single slash? Does it work if you do this:

`let install_script = "/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py"`

**Comment by moeshin** [comment]
no. `let install_script = "/C/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py"` is work

**Comment by alanhamlett** [comment]
Can you try now after a3e2c1200965b08d75dea2c443bb38acd4b950e1?

**Comment by alanhamlett** [comment]
Can you try now after 36f7f5ce85563b8ca927263cf94e15034dbcb0ff?

**Comment by moeshin** [comment]
no

**Comment by alanhamlett** [comment]
That's strange, I thought it would be the fix.

Can you add line:
`echo install_script` just after the `let install_script`?

**Comment by moeshin** [comment]
```
install_script: C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py
```

**Comment by alanhamlett** [comment]
You've removed the override from before? Want to make sure this line is deleted:
`let install_script = "/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py"`

**Comment by alanhamlett** [comment]
I'm not sure how it could remove the `/c/Users/MoeShin/` prefix and be left with `C:/` with a colon and no starting slash...

Maybe the `substitute` from 36f7f5ce85563b8ca927263cf94e15034dbcb0ff isn't running and the path changed some other way?

**Comment by moeshin** [comment]
Run console
```cmd
C:\Users\MoeShin>python3 C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py
python3: can't open file '/c/Users/MoeShin/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py': [Errno 2] No such file or directory
```

**Comment by moeshin** [comment]
https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1006869727

**Comment by alanhamlett** [comment]
Oh, Python is the one adding the duplicate drive prefix not Vim. That's why 36f7f5ce85563b8ca927263cf94e15034dbcb0ff isn't matching.

So in https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1006886055 you said just removing `:` works?

We need a way to detect MSYS2 Python without executing Python, since that would cause slow startup issues.

What's the location of your python when you run `where python3`?

**Comment by moeshin** [comment]
```text
C:\Users\MoeShin>where python3
D:\msys64\usr\bin\python3.exe
C:\Users\MoeShin\scoop\shims\python3.exe
C:\Users\MoeShin\AppData\Local\Microsoft\WindowsApps\python3.exe

❯ where python3
/usr/bin/python3
/bin/python3
/c/Users/MoeShin/scoop/shims/python3
/c/Users/MoeShin/AppData/Local/Microsoft/WindowsApps/python3
```

**Comment by moeshin** [comment]
```text
❯ python3 -VV
Python 3.9.9 (main, Nov 21 2021, 19:18:40)
[GCC 10.2.0]

❯ scoop/shims/python3 -VV
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
```

**Comment by moeshin** [comment]
```text
C:\Users\MoeShin>python3
Python 3.9.9 (main, Nov 21 2021, 19:18:40)
[GCC 10.2.0] on cygwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.system()
'MSYS_NT-10.0-22523'
>>> import os
>>> os.name
'posix'


C:\Users\MoeShin>scoop\shims\python3.exe
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.system()
'Windows'
>>> import os
>>> os.name
'nt'
```

**Comment by alanhamlett** [comment]
So the first section is the normal Windows cmd prompt and the other is MSYS2?

You're running Vim/Nvim from within MSYS2 right, not just Python? I'm trying to find a way to detect MSYS2 Python without executing any sub process, so we don't slow down Vim startup for all Windows users.

The Windows cmd prompt path to python3 `D:\msys64\usr\bin\python3.exe` references msys but `❯ where python3` doesn't.

**Comment by alanhamlett** [comment]
How about now after c9a88e1b3ba704a001f54b33ddf53e6b4d8a24cb?

**Comment by moeshin** [comment]
Remove ` && &shell =~ 'cmd'` in `elseif s:nvim_async` to fix
```text
[WakaTime] 127: /usr/bin/zsh: can't open input file: /s /c
```
https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1006778849
Revert c1c60ca9

**Comment by moeshin** [comment]
Or overwrite shell and shellcmdflag

```vim
if has('win32')
    let &shell = 'cmd.exe'
    let &shellcmdflag = '/s /c'
endif
```

**Comment by alanhamlett** [comment]
Done with 877967af2f87dc7593721532238e2c73bb073b8e.

**Comment by moeshin** [comment]
```text
[WakaTime] 2: /usr/bin/python3: can't open file '//Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py': [Errno 2] No such file or directory
```

**Comment by moeshin** [comment]
The vim installed by scoop on msys2.
```
[WakaTime] /usr/bin/zsh: can't open input file: /c
```
-------
```vim
echo &shell
" D:/msys64/usr/bin/zsh

" Run in Script
echo &shellcmdflag
" /c

" Run normal mode
:echo &shellcmdflag
" -c
```

I think should overwrite `shell` and `shellcmdflag`.

https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007184948

**Comment by moeshin** [comment]
```vim
let install_script = substitute(install_script, '^\([A-Z]\):', '/\1', '')

echo substitute('C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py', '^\([A-Z]\):', '/\1', '')
" /C/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py
```

**Comment by moeshin** [comment]
```vim
if s:IsWindows() && exepath(python_bin) =~ '[/\\]bin'
    " MSYS2
    let install_script = substitute(install_script, '^\([A-Z]\):', '/\1', '')
endif
```

**Comment by alanhamlett** [comment]
I'm sorry, I had a bug in my regex. Fixed with 1316c0545108c532ee97cf6451e40bea688c5785.

**Comment by moeshin** [comment]
Run 1316c05

* [x] zsh+nvim(scoop)
* [x] zsh+vim(msys2)
* [x] cmd+vim(msys2)
* [ ] zsh+vim(scoop)
```text
[WakaTime] /usr/bin/zsh: can't open input file: /c
```
* [ ] cmd+nvim(scoop)
* [ ] cmd+vim(scoop)
```text
[WakaTime] 2: /usr/bin/python3: can't open file '/c/Users/MoeShin/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py': [Errno 2] No such file or directory
```

**Comment by alanhamlett** [comment]
Can you re-run those tests with a0daba95d17aaa59f99769caee28c92763595b18?

**Comment by alanhamlett** [comment]
Also, would be helpful for each of the checkboxes above to have the values of `&shell` and `&shellcmdflag`. Just once, like your comment above please 😄

**Comment by moeshin** [comment]
Run a0daba9

```vim
echom '`'.&shell.'`+`'.&shellcmdflag.'`'
```

* [x] zsh+vim(msys2)+`/usr/bin/zsh`+`-c`
* [x] zsh+vim(scoop)+`D:/msys64/usr/bin/zsh`+`-c`
* [x] zsh+nvim(scoop)+`D:/msys64/usr/bin/zsh`+`/s /c`
* [x] cmd+vim(msys2)+`sh`+`-c`
* [ ] cmd+vim(scoop)+`C:\WINDOWS\system32\cmd.exe`+`/c`
* [ ] cmd+nvim(scoop)+`cmd.exe`+`/s /c`
```text
[WakaTime] 2: /usr/bin/python3: can't open file '/c/Users/MoeShin/C:/Users/MoeShin/.vim/plugged/vim-wakatime/scripts/install_cli.py': [Errno 2] No such file or directory
```

**Comment by moeshin** [comment]
Currently this bug is caused by the python version (installed by pacman on msys2).
------
And the msys2 installation folder can be customized https://www.msys2.org/.
May not contain `msys`.
> Enter your desired Installation Folder (short ASCII-only path on a NTFS volume, no accents, no spaces, no symlinks, no subst or network drives, no FAT).

**Comment by alanhamlett** [comment]
Could you also run the same echo shell test with `echo s:plugin_root_folder`?

**Comment by alanhamlett** [comment]
> And the msys2 installation folder can be customized https://www.msys2.org/. May not contain `msys`.

Oh, that makes things much more difficult. I'm just worried about overwriting `&shell` for all Windows users, in case `cmd.exe` isn't in their path and we break things for someone.

We also can't run `system()` in the foreground during startup, but maybe we can async run `python -VV`.

**Comment by moeshin** [comment]
```text
cmd+vim(msys2)
s:IsMSYS(): 0
s:plugin_root_folder: /c/Users/MoeShin/.vim/plugged/vim-wakatime

cmd+vim(scoop)
s:IsMSYS(): 0
s:plugin_root_folder: C:/Users/MoeShin/.vim/plugged/vim-wakatime

cmd+nvim(scoop)
s:IsMSYS(): 0
s:plugin_root_folder: C:/Users/MoeShin/.vim/plugged/vim-wakatime

zsh+vim(msys2)
s:IsMSYS(): 0
s:plugin_root_folder: /c/Users/MoeShin/.vim/plugged/vim-wakatime

zsh+vim(scoop)
s:IsMSYS(): 1
s:plugin_root_folder: /C/Users/MoeShin/.vim/plugged/vim-wakatime

zsh+nvim(scoop)
s:IsMSYS(): 1
s:plugin_root_folder: /C/Users/MoeShin/.vim/plugged/vim-wakatime
```

In vim(msys2)
```vim
has('win32') == 0
has('unix') == 1
```

**Comment by moeshin** [comment]
Or re-run with unix style path when python exit code == 2

**Comment by moeshin** [comment]
zsh+vim(msys2)
```vim
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" -c
```

zsh+vim(scoop)
```vim
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" At startup:
" /c
" After startup:
" -c
```

zsh+nvim(scoop)
```vim
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" /s /c
```

cmd+vim(msys2)
```vim
echo &shell
" C:\WINDOWS\system32\cmd.exe

echo &shellcmdflag
" /c
```

cmd+vim(scoop)
```vim
echo &shell
" C:\WINDOWS\system32\cmd.exe

echo &shellcmdflag
" /c
```

cmd+nvim(scoop)
```vim
echo &shell
" cmd.exe

echo &shellcmdflag
" /s /c
```

**Comment by alanhamlett** [comment]
> > I'm just worried about overwriting &shell for all Windows users, in case cmd.exe isn't in their path and we break things for someone.
> 
> Or override `shellcmdflag`?

Can't overwrite `&shellcmdflag` without also `&shell` because they're tied together:
https://vimhelp.org/options.txt.html#%27shell%27

**Comment by moeshin** [comment]
```vim
if &shell =~ 'sh\(.exe\)\?$'
    let &shellcmdflag = '-c'
endif
```

**Comment by moeshin** [comment]
```vim
if s:has_async
    if !s:IsWindows()
        let job_cmd = [&shell, &shellcmdflag, s:JoinArgs(cmd)]
    elseif &shell =~ 'sh\(.exe\)\?$' " or &shell !~ 'cmd\(.exe\)\?$'
        let job_cmd = [&shell, '-c', s:JoinArgs(cmd)]
    else
        let job_cmd = [&shell, &shellcmdflag] + cmd
    endif
elseif s:nvim_async
    if s:IsWindows()
        let job_cmd = cmd
    else
        let job_cmd = [&shell, &shellcmdflag, s:JoinArgs(cmd)]
    endif
endif
```

**Comment by alanhamlett** [comment]
That works for all variants?

**Comment by moeshin** [comment]
> ```viml
> if &shell =~ 'sh\(.exe\)\?$'
>     let &shellcmdflag = '-c'
> endif
> ```

This way has bug in nvim.

```vim
:!ls .
" no work: zsh:1: command not found: ls .

:!'ls .'
" no work: zsh:1: command not found: 'ls .'

:!"ls ."
" work
```

**Comment by moeshin** [comment]
> That works for all variants?

Yes

**Comment by alanhamlett** [comment]
> > That works for all variants?
> 
> Yes

With that change, do we still need to replace `C:/` with `/C/`?

**Comment by moeshin** [comment]
Python msys still needs

**Comment by moeshin** [comment]
Normal python does not need

```text
python3 -VV
Python 3.10.1 (tags/v3.10.1:2cd268a, Dec  6 2021, 19:10:37) [MSC v.1929 64 bit (AMD64)]
```

**Comment by alanhamlett** [comment]
Which of the variants from https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007594481 or https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007563678 are python msys?

**Comment by moeshin** [comment]
python doesn't affect these

**Comment by moeshin** [comment]
It's two problems:
* execute command in vim or nivm. solve by https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007627905
* python (install by pacman on msys2), the script path should unix-style. solve by https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007247697 ?

**Comment by alanhamlett** [comment]
Fixed the first problem with a17a43663819923d1dedfc14591a0a605c7bbdc9.

Fixed the second problem with 441f5c7ce8adce1d30403bca26ea5e6a3a2b82e4.

**Comment by alanhamlett** [comment]
Thanks again for your help fixing this!

**Comment by moeshin** [comment]
Thanks you.

a17a436 only fix `job_start` and `jobstart`.
There may also be a first problem with calling `system()` in nvim on bash, git-bash or zsh. https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007594481
```vim
echo &shell
" D:/msys64/usr/bin/zsh

echo &shellcmdflag
" /s /c

echo system('ls .')
" /usr/bin/bash: /s: No such file or directory
```

If overwrite `let &shellcmdflag = '-c'`, there will be problems https://github.com/wakatime/vim-wakatime/issues/122#issuecomment-1007632839

https://github.com/wakatime/vim-wakatime/blob/441f5c7ce8adce1d30403bca26ea5e6a3a2b82e4/plugin/wakatime.vim#L771

In nvim, the type of cmd can be string or list.

```vim
let &shellcmdflag = '-c'

echo system('ls .') " no work

echo system(['ls', '.']) " work
```

```vim
function! g:System(cmd)
    " cmd is list
    let override = s:false
    if has('nvim')
        if has('win32') && &shell !~ 'cmd\(.exe\)\?$' && &shellcmdflag !~ '^\s*-'
            let override = s:true
            let _shellcmdflag = &shellcmdflag
            let &shellcmdflag = '-c'
        endif
    else
        let a:cmd = s:JoinArgs(a:cmd)
    endif
    let data = system(a:cmd)
    if override
        let &shellcmdflag = _shellcmdflag
    endif
    return data
endfunction
```

**Comment by alanhamlett** [comment]
Doesn't Nvim always have support for async? Then it would never reach `system()` on nvim... only on older Vim without async.

**Comment by moeshin** [comment]
ok
