### ISSUE TITLE
Error Sending heartbeats

### ISSUE THREAD

**Issue by opti21** [wakatime/vim-wakatime#126]
Error detected while processing function <SNR>68_SendHeartbeats:
line   71:
E475: Invalid value for argument cmd: 'C:/Users/opti/.wakatime/wakatime-cli.exe' is not executable

**Comment by opti21** [comment]
Just had to remove the ~/.wakatime folder and reinstall

**Comment by alanhamlett** [comment]
If it happens again, please share the contents of your .wakatime folder since this might still be a bug.

**Comment by WanderLanz** [comment]
Ooh fun I managed to get this as well, "$HOME\.wakatime\" has only "vim_shared_state" and "wakatime-cli-windows-amd64.exe", so maybe some weird windows thing deleting the "wakatime-cli.exe" symlink or not creating the symlink correctly with Plug or Packer or what have you.

seems like it doesn't have anything to do with wakatime plugin. God knows what happened.
The error is just misleading, that's about the only thing I think can be fixed.

**Comment by wleoncio** [comment]
Removing `$HOME/.wakatime` wasn't enough on a particular system I use. I also had to manually change the file permissions to give myself `rwx` access:

```
chmod 771 $HOME/.wakatime
```

BTW, perhaps you can get away lower permissions for group and others (my local machine has 751 on that folder, for example).

**Comment by luchaoqi** [comment]
Same error here. After removing `.wakatime`, you may still need to create the folder manually to solve the privilege problem: `mkdir .wakatime`
