### ISSUE TITLE
Today: zsh:1: permission denied: /Users/parkerbjur/.wakatime/wakatime-cli

### ISSUE THREAD

**Issue by parkerbjur** [wakatime/vim-wakatime#127]
I just installed vim-wakatime using vim-plug for neovim. I added my API-key to the config file but the stats don't seem to be uploading to the dashboard. I tried running the :WakaTimeToday command and get this error: `Today: zsh:1: permission denied: /Users/parkerbjur/.wakatime/wakatime-cli`

**Comment by alanhamlett** [comment]
What happens when you run the `scripts/install_cli.py` script from a terminal with `debug=true` in your `~/.wakatime.cfg` file?

**Comment by alanhamlett** [comment]
Also, what's the output of `ls -la ~/.wakatime`?

**Comment by parkerbjur** [comment]
terminal output of `ls -la ~/.wakatime`
>total 35424
>drwxr-xr-x   4 parkerbjur  staff       128 Jan 14 15:19 .
>drwxr-xr-x+ 47 parkerbjur  staff      1504 Jan 21 10:11 ..
>drwxr-xr-x  71 parkerbjur  staff      2272 May 25  2021 wakatime-cli
>-rwxr-xr-x   1 parkerbjur  staff  18134288 Jan  7 16:40 wakatime-cli-darwin-amd64


terminal output of `python3 install_cli.py`
>[WakaTime] Current wakatime-cli version is v1.35.0
>[WakaTime] Checking for updates to wakatime-cli...
>[WakaTime] GitHub API Response 304
>[WakaTime] wakatime-cli is up to date.

wakatime.log if that is useful
>{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:74","func":"Run","level":"debug","message":"command: version","now":"2022-01-21T10:17:17-08:00","version":"v1    .35.0"}
>{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/run.go:74","func":"Run","level":"debug","message":"command: version","now":"2022-01-21T10:18:31-08:00","version":"v1    .35.0"}

**Comment by parkerbjur** [comment]
Also here is the log from when I initially installed wakatime-vim if that is useful

> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:182","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","now":"2021-07-02T09:01:37-07:00","version":"<local-build>"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:182","func":"runCmd","level":"error","message":"failed to run command: failed to fetch today summary: failed fetching summaries from api: failed to make request to \"https://api.wakatime.com/api/v1/users/current/summaries\": Get \"https://api.wakatime.com/api/v1/users/current/summaries?end=2021-07-02&start=2021-07-02\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","now":"2021-07-02T09:02:03-07:00","version":"<local-build>"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:215","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","now":"2021-07-02T09:02:37-07:00","version":"<local-build>"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:182","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): file '/Users/parkerbjur/code/IsoPathApi/interaction/listeners.js' does not exist. ignoring this heartbeat","now":"2021-07-02T10:23:17-07:00","version":"<local-build>"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:182","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): file '/Users/parkerbjur/code/IsoPathApi/interaction/listeners.js' does not exist. ignoring this heartbeat","now":"2021-07-02T10:23:18-07:00","version":"<local-build>"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:51427->[::1]:53: read: connection refused","now":"2021-07-05T16:10:23-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:63580->[::1]:53: read: connection refused","now":"2021-07-05T16:10:23-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:60614->[::1]:53: read: connection refused","now":"2021-07-05T16:12:24-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:50923->[::1]:53: read: connection refused","now":"2021-07-05T16:12:24-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:49273->[::1]:53: read: connection refused","now":"2021-07-05T16:12:46-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:51639->[::1]:53: read: connection refused","now":"2021-07-05T16:12:46-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:62652->[::1]:53: read: connection refused","now":"2021-07-05T16:14:04-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:54541->[::1]:53: read: connection refused","now":"2021-07-05T16:14:04-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:59607->[::1]:53: read: connection refused","now":"2021-07-05T16:14:07-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:58256->[::1]:53: read: connection refused","now":"2021-07-05T16:14:07-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:58522->[::1]:53: read: connection refused","now":"2021-07-05T16:14:34-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:51670->[::1]:53: read: connection refused","now":"2021-07-05T16:14:34-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:53495->[::1]:53: read: connection refused","now":"2021-07-05T16:16:35-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:64594->[::1]:53: read: connection refused","now":"2021-07-05T16:16:35-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:61127->[::1]:53: read: connection refused","now":"2021-07-05T16:16:58-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:55099->[::1]:53: read: connection refused","now":"2021-07-05T16:16:58-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:64387->[::1]:53: read: connection refused","now":"2021-07-05T16:17:34-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:54513->[::1]:53: read: connection refused","now":"2021-07-05T16:17:34-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:54907->[::1]:53: read: connection refused","now":"2021-07-05T16:17:40-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:64871->[::1]:53: read: connection refused","now":"2021-07-05T16:17:40-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:57572->[::1]:53: read: connection refused","now":"2021-07-05T16:18:28-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:58260->[::1]:53: read: connection refused","now":"2021-07-05T16:18:28-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:54250->[::1]:53: read: connection refused","now":"2021-07-05T16:18:42-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:63071->[::1]:53: read: connection refused","now":"2021-07-05T16:18:42-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:57387->[::1]:53: read: connection refused","now":"2021-07-05T16:20:39-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:65493->[::1]:53: read: connection refused","now":"2021-07-05T16:20:39-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:49693->[::1]:53: read: connection refused","now":"2021-07-05T16:20:53-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:51827->[::1]:53: read: connection refused","now":"2021-07-05T16:20:53-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:64153->[::1]:53: read: connection refused","now":"2021-07-05T16:21:46-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:51087->[::1]:53: read: connection refused","now":"2021-07-05T16:21:46-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:53176->[::1]:53: read: connection refused","now":"2021-07-05T16:21:57-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:56764->[::1]:53: read: connection refused","now":"2021-07-05T16:21:57-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:54815->[::1]:53: read: connection refused","now":"2021-07-05T16:22:03-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:59179->[::1]:53: read: connection refused","now":"2021-07-05T16:22:03-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:55083->[::1]:53: read: connection refused","now":"2021-07-05T16:22:04-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:64985->[::1]:53: read: connection refused","now":"2021-07-05T16:22:04-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:55879->[::1]:53: read: connection refused","now":"2021-07-05T16:22:05-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:52749->[::1]:53: read: connection refused","now":"2021-07-05T16:22:05-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:50133->[::1]:53: read: connection refused","now":"2021-07-05T16:22:13-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:52714->[::1]:53: read: connection refused","now":"2021-07-05T16:22:13-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:189","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:55155->[::1]:53: read: connection refused","now":"2021-07-05T16:22:23-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:225","func":"sendDiagnostics","level":"error","message":"failed to send diagnostics: failed making request to \"https://api.wakatime.com/api/v1/plugins/errors\": Post \"https://api.wakatime.com/api/v1/plugins/errors\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:50223->[::1]:53: read: connection refused","now":"2021-07-05T16:22:23-07:00","version":"v1.18.7"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:79","func":"SendHeartbeats","level":"warning","message":"file 'Untitled-1' does not exist. ignoring this heartbeat","now":"2021-09-05T10:03:42-07:00","version":"v1.22.1"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/heartbeat/heartbeat.go:79","func":"SendHeartbeats","level":"warning","message":"file 'Untitled-1' does not exist. ignoring this heartbeat","now":"2021-09-05T10:04:31-07:00","version":"v1.22.1"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:65377->[::1]:53: read: connection refused","now":"2021-09-05T16:45:32-07:00","version":"v1.22.1"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:56186->[::1]:53: read: connection refused","now":"2021-09-05T16:46:19-07:00","version":"v1.22.1"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: won't send heartbeat due to backoff","now":"2021-09-05T16:46:25-07:00","version":"v1.22.1"}
> {"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp: lookup api.wakatime.com on [::1]:53: read udp [::1]:63947->[::1]:53: read: connection refused","now":"2021-09-05T16:48:31-07:00","version":"v1.22.1"}

**Comment by alanhamlett** [comment]
Make sure your vim-wakatime is up to date, then try deleting the directory `~/.wakatime/` then restart Vim. Does that fix things?

**Comment by parkerbjur** [comment]
Thanks! I suppose I should've tried 'reinstall' it. Works perfectly now.
