### ISSUE TITLE
There is no installation guide for Packer manager for Neovim.

### ISSUE THREAD

**Issue by nishu-murmu** [wakatime/vim-wakatime#129]
I want to install waka-time plugin for Neovim and am using latest lua environment with packer manager in Neovim. But there isn't one. Can someone create such option.

**Comment by alanhamlett** [comment]
Does this work? https://stackoverflow.com/a/50122211/1290627

**Comment by nishu-murmu** [comment]
It helped. Though you add in docs for packer manager as well.
