### ISSUE TITLE
WakaTimeToday permission denied

### ISSUE THREAD

**Issue by harryghgim** [wakatime/vim-wakatime#131]
Hi. Thanks for the great vim plugin. 

My issue is even if I registered my api key, my wakatime dashboard won't show the sign of vim as registered editor. I ran `:WakaTimeApiKey` and pasted my api key from dashboard, and also made sure that my `~/.wakatime.cfg` has `api_key`value in it.

I use wakatime with vscode and sublime text, and no such non-recognition issue happened with them.

And as a related issue I suspect, when I run `:WakaTimeToday`, I see this sign on the bottom:
```
Today: zsh:1: permission denied: /Users/gwanghyeongim/.wakatime/wakatime-cli
```

But when I run this file in shell, it seems at least I don't have permission error. 

What do you think seems to be the reason of the problem?

For better reproduction of the issue my environments are as follow:
- macOs Cataliana Version 10.15.7
- Vim 8.2

**Comment by kidonng** [comment]
Try setting [the symlink](https://github.com/wakatime/vim-wakatime/commit/7a6d776a6a36d432cad3ef1e7c926f6d777e57bc) yourself:

```sh
ln -s (basename ~/.wakatime/*) ~/.wakatime/wakatime-cli
```

The symlink will be created automatically if you install the CLI via this plugin.

**Comment by alanhamlett** [comment]
@harryghgim try adding `debug = true` to your `~/.wakatime.cfg` file then start Vim and look for an error message at the bottom.

Every time vim-wakatime loads (on Vim startup) it runs [this install script](https://github.com/wakatime/vim-wakatime/blob/b6754ace510ffa931bceb47df417a9ef3a87cb6b/scripts/install_cli.py) which should create the symlink. If it's failing there should be an error printed with `debug = true`.

**Comment by harryghgim** [comment]
> @harryghgim try adding `debug = true` to your `~/.wakatime.cfg` file then start Vim and look for an error message at the bottom.
> 
> Every time vim-wakatime loads (on Vim startup) it runs [this install script](https://github.com/wakatime/vim-wakatime/blob/b6754ace510ffa931bceb47df417a9ef3a87cb6b/scripts/install_cli.py) which should create the symlink. If it's failing there should be an error printed with `debug = true`.

@alanhamlett After I set `debug = true` in cfg file, no earlier than I had set `let g:wakatime_CLIPath='/Users/gwanghyeongim/.wakatime/wakatime-cli'` in my vimrc, I see this error message. Maybe my path is wrong somehow?

<img width="1440" alt="Screen Shot 2022-02-22 at 12 43 38 AM" src="https://user-images.githubusercontent.com/35060447/154987633-e36ca289-ba43-469e-be67-ad955bb08fe0.png">

@kidonng I ran the command, and the result says 
```
ln: /Users/gwanghyeongim/.wakatime/wakatime-cli/wakatime-cli: File exists
```
So I tried g:wakatime_CLIPath as above, it doesn't seem to help me much either. 

I have a feeling that I've missed something too obvious to miss in the end...

**Comment by alanhamlett** [comment]
That error shown is:
`Error: sh: /Users/gwanghyeongim/.wakatime/wakatime-cli: is a directory`

Try deleting your `~/.wakatime/` folder then re-launch Vim.

**Comment by harryghgim** [comment]
@alanhamlett Thank you so much. My issue is solved now and I'm closing it.

**Comment by alanhamlett** [comment]
Also, remember to turn off debug mode so your Vim performance won't be impacted:

`:WakaTimeDebugDisable`

**Comment by alanhamlett** [comment]
f922f82954cb68fccfd20ad3eacc78fb2559a937 should prevent this from happening in the future.

**Comment by OGoodness** [comment]
Having a similar issue, it's trying to run the folder instead of running the binary inside of the folder
