### ISSUE TITLE
Error detected while processing function <SNR>30_SendHeartbeats:

### ISSUE THREAD

**Issue by technbuzz** [wakatime/vim-wakatime#136]
I am trying to Install neovim-wakatime on windows. I followed all the instruction but now I am getting following error
![Screenshot 2022-03-21 151155](https://user-images.githubusercontent.com/1523391/159250051-69ecd439-5499-42be-afdd-efe99185fecb.png)

Further more, it's kinda stuck in the loop, every time I open nvim, I get following message to install wakatime-cli while it's already there
![loop](https://user-images.githubusercontent.com/1523391/159250443-97215e17-6638-428d-87e8-38e501c420ab.png)

**Comment by alanhamlett** [comment]
Let's debug this:

* What's the contents of your `~/.wakatime/` folder?
* Can you run `~/.wakatime/wakatime-cli.exe --version` without errors from a terminal?
* What errors do you see on nvim startup after adding `debug = true` to your `~/.wakatime.cfg` file?

**Comment by technbuzz** [comment]
- The content of `~/.wakatime` folder is `wakatime-cli-windows-amd64.exe`
- Yes it runs and I see 
![image](https://user-images.githubusercontent.com/1523391/165283650-427adc9d-15ed-4da3-8b48-2c1f00ef4ae1.png)

- After setting debug: true I get
![image](https://user-images.githubusercontent.com/1523391/165284159-e3c7aa4b-6468-42b5-b431-67de19ef37f2.png)


- After using the app I get following SNR issue
![image](https://user-images.githubusercontent.com/1523391/165284107-fb1230f7-8319-4218-8459-defb4ed22754.png)

I tried the *Administrator* mode as well, but nothing

**Comment by alanhamlett** [comment]
What happens when you run `Scripts/install_cli.py` from Terminal now that debug is enabled?

**Comment by technbuzz** [comment]
Where can I find this file?

**Comment by alanhamlett** [comment]
It's in your vim-wakatime installation folder, wherever you've configured vim plugins to live. For me, that's `~/.vim/plugins/vim-wakatime/Scripts/install_cli.py` where `~` is my user home folder.

**Comment by technbuzz** [comment]
Okay, that is what I get
![image](https://user-images.githubusercontent.com/1523391/166122673-80bd2048-4663-4066-863d-e11bc1d7d90a.png)

**Comment by alanhamlett** [comment]
Is your `vim-wakatime` up to date? There were some changes to the install script that should have fixed the missing symlink recently.

**Comment by technbuzz** [comment]
that's what I get when I ran vimplug update command, btw i am uisng `nvim 0.6.1`
![image](https://user-images.githubusercontent.com/1523391/166930207-7b87e6c5-0b94-4e48-a7f6-8d9309f13984.png)

**Comment by alanhamlett** [comment]
Is the error still occurring now after having upgraded?

**Comment by rauf-21** [comment]
>  The content of `~/.wakatime` folder is `wakatime-cli-windows-amd64.exe`

@technbuzz, try renaming the file from 'wakatime-cli-windows-amd64.exe' to 'wakatime-cli.exe'. It works after I change the filename.

**Comment by alanhamlett** [comment]
That `improve urllib usage` change log wasn't the latest version, so it didn't have the fix. I'll close this for now, but let me know if I should re-open this issue after making sure you're using the latest plugin version.

**Comment by technbuzz** [comment]
> > The content of `~/.wakatime` folder is `wakatime-cli-windows-amd64.exe`
> 
> @technbuzz, try renaming the file from 'wakatime-cli-windows-amd64.exe' to 'wakatime-cli.exe'. It works after I change the filename.

Thanks @rauf-21 it works with suggested fix. I don't know whether the future version will already take care of this.
