### ISSUE TITLE
Error detected while processing function <SNR>46_HandleActivity(10]..<SNR>46_AppendHeartbeat(18]..<SNR>46_SetLastHeartbeat:

### ISSUE THREAD

**Issue by alexventuraio** [wakatime/vim-wakatime#137]
I recently installed NeoVim via homebrew and installed the vim-wakatime pluging via Vim-Plug.
I have wakatime working correctly for VIM and VSCode so I just installed the pluging but it asked me for the API KEY which was supposed to be there because config files already exist.

I'm getting this error now:
```vim
Error detected while processing function <SNR>46_HandleActivity(10]-.<SNR>46_AppendHeartbeat(18]..<SNR>46_SetLastHeartbeat:
line
2:
E482: Can't open file $HOME/.wakatime.data for writing: no such file or directory
Press ENTER or type command to continue
```

Does anyone know how to fix it?

This is my CFG file:
```sh
[settings]
debug         = false
hidefilenames = false
ignore        = """
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$"""
api_key       = xxxxxxxxxx

[internal]
backoff_retries = 0
backoff_at      = 
```

**Comment by alanhamlett** [comment]
> Should it be enough to update the plugin on my machine to fix it?

Yep :)
