### ISSUE TITLE
Cannot create directory: ~/.wakatime

### ISSUE THREAD

**Issue by iaGuoZhi** [wakatime/vim-wakatime#140]
I installed wakatime in my vim editor, and the ~/.wakatime is created automatically when plugin installed. However the following error occurs repeatedly when I use vim.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/41318515/170874344-cbc08912-6c92-447a-9674-2e3d7d8e863a.png">

Is there anything that could have gone wrong？

Here is my environments:

OS: Ubuntu 18.04
VIM: VIM 8.0

Thanks!

**Comment by alanhamlett** [comment]
Should be fixed with f86ca61010beac4ba9633dae2be74d1ce57b18fe. Can you update the plugin and let me know if the error is gone?

**Comment by iaGuoZhi** [comment]
> Should be fixed with [f86ca61](https://github.com/wakatime/vim-wakatime/commit/f86ca61010beac4ba9633dae2be74d1ce57b18fe). Can you update the plugin and let me know if the error is gone?

It works, Thanks!
