### ISSUE TITLE
Projects With Git Worktree Not Working Correctly

### ISSUE THREAD

**Issue by roeeyn** [wakatime/vim-wakatime#142]
Hi!
I've been using wakatime for  a while, and I noticed that my projects using worktrees and not been detected correctly.

![image](https://user-images.githubusercontent.com/13385000/179006894-73fadae1-03ea-49dd-bf76-51709720be62.png)

In my dashboard it appears that `main` is my project, but it is the name of the branch of a couple different projects. My projects are like the following:

- `~/src/project1/main`
- `~/src/project2/main`
- `~/src/project3/main`

I noticed that in the PR wakatime/wakatime-cli#61 the support for worktrees were included, but find no more information if special setup was needed. Please let me know if you need any more info. Thanks in avance!

**Comment by alanhamlett** [comment]
Could you share this repo, or create a new open source repo on GitHub with the same worktree structure, so that I can test and reproduce the issue?

**Comment by roeeyn** [comment]
Trying to help a little more, I think I probably found the issue. Assuming I have the following project:

`/Users/roeeyn/src/my_project/main/`, where `my_project` is the name of my project, and `main` is the name of my git worktree/branch. I will have a `.git` file here `/Users/roeeyn/src/my_project/main/.git`. This git file looks something like this: 

```
gitdir: /Users/roeeyn/src/my_project/worktrees/main
```

Inside `wakatime-cli`, after validating we're not using submodules, and after searching for `.git/config`, we're looking for the `gitdir` [here](https://github.com/wakatime/wakatime-cli/blob/release/pkg/project/git.go#L78-L85).

After looking for `commondir` and validating the `gitdir` is not empty, we just fall back to using the top directory as the project name [here](https://github.com/wakatime/wakatime-cli/blob/release/pkg/project/git.go#L116-L118), which in the case I just mentioned, would be `main` because it is the top directory. 

Please let me know what you think. Thanks again!

**Comment by gandarez** [comment]
Yep it seem to be a priority problem. I'm already taking care of it, thanks for sharing your thoughts.

**Comment by alanhamlett** [comment]
> we just fall back to using the top directory as the project name

Great find! That looks to be the issue. I'm sure @gandarez already has a fix in mind.
