### ISSUE TITLE
Error while installing Wakatime in NeoVim

### ISSUE THREAD

**Issue by hditano** [wakatime/vim-wakatime#145]
Hello everyone.
This is the error I'm getting while installing Wakatime in Neovim using Packer.nvim (:PackerSync)

```
Error detected while processing /home/hditano/.local/share/nvim/site/pack/packer/start/vim-wakatime/plugin/wakatime.vim[857]..function <SNR>40_InstallCLI:
line   46:
E475: Invalid value for argument cmd: 'fish' is not executable
```

Thx!!

**Comment by alanhamlett** [comment]
It's probably the `&shell` not found:
https://github.com/wakatime/vim-wakatime/blob/4692ec3e77ade9e65171182296cca74352a39a12/plugin/wakatime.vim#L171

What's your default terminal shell?

**Comment by hditano** [comment]
> It's probably the `&shell` not found:
> 
> https://github.com/wakatime/vim-wakatime/blob/4692ec3e77ade9e65171182296cca74352a39a12/plugin/wakatime.vim#L171
> 
> What's your default terminal shell?

Hello!

I'm using zsh.

**Comment by alanhamlett** [comment]
What happens if you run the install python script manually?

**Comment by hditano** [comment]
> What happens if you run the install python script manually?

I tried with Python3 install_cli.py -> nvim -> still error.

**Comment by alanhamlett** [comment]
But now it tracks your Vim usage after ignoring the error in Nvim?

**Comment by hditano** [comment]
> But now it tracks your Vim usage after ignoring the error in Nvim?

Alan.. Just reinstalled everything from zero. Deleted the proper folder where everything related to wakatime was. (whereis wakatime).
Reinstalled everything as usual using Packer.nvim, still got the same error, then manually installed the script (Python3 install_cli_py).
Error was still there, went to wakatime.cfg, added my API KEY manually.
Even tho I still get the same error while executing Neovim, I am able to track time as usual now.

Thx

**Comment by alanhamlett** [comment]
Let's try this: Inside NVim type:

    :echo &shell

And let me know what is printed at the bottom. The error happens when NVim is trying to run the install script on startup, and I think it's related to that `%shell` builtin.

**Comment by hditano** [comment]
> Let's try this: Inside NVim type:
> 
> ```
> :echo &shell
> ```
> 
> And let me know what is printed at the bottom. The error happens when NVim is trying to run the install script on startup, and I think it's related to that `%shell` builtin.

Fixed it!!

Forgot to change 'fish' for 'zsh'
After doing that, no more error messages!!

![image](https://user-images.githubusercontent.com/6069906/186537272-86ca8c38-68bf-4670-851d-b08f9c027010.png)
