### ISSUE TITLE
How to install with SpaceVim

### ISSUE THREAD

**Issue by algoflows** [wakatime/vim-wakatime#149]
Using SpaceVim here, can't install this anyway a I try.

![Screenshot 2022-11-10 at 20 14 42](https://user-images.githubusercontent.com/65465380/201196702-69cb4ecd-c63d-4326-acf8-cc81ee73d8fd.png)

**Comment by alanhamlett** [comment]
Added install instructions for SpaceVim here:
https://wakatime.com/vim#spacevim-install
