### ISSUE TITLE
Error detected while processing function <SNR>57_InstallCLI

### ISSUE THREAD

**Issue by jeeeem** [wakatime/vim-wakatime#151]
I commented this in #141 but I think its better if I create another bug issue for noticeability

![image](https://user-images.githubusercontent.com/51053482/203348783-aa80f067-7c84-4bc4-85d2-c468e2d29645.png)

I encountered this error and I tried running the script with `debug=true`.

I already did it once and it installed successfully that why this is the result. The thing I also had the same neovim config in my other machine but it works perfectly and same dev env setup so I'm not sure why is this occuring

![image](https://user-images.githubusercontent.com/51053482/203349026-aa58764d-5f03-4b68-899e-2b2bf3fbc80c.png)

OS: Windows 11
Nvim: v0.9.0-dev-356+g6e8ed5aba
Shell: Powershell 7.3

**Comment by alanhamlett** [comment]
What's the output when you run these commands inside Neovim:

`:echo has('python3')`

`:python3 print("has python 3")`

**Comment by jeeeem** [comment]
Thanks for hinting the solution. Already solve this by not using pyenv python version.
