### ISSUE TITLE
Wakatime not working with Packer in neovim?

### ISSUE THREAD

**Issue by 0ussamaBernou** [wakatime/vim-wakatime#152]
i added ` use 'wakatime/vim-wakatime' ` to ` ~/.config/nvim/lua/plugins.lua `
and also added it to ` ~/.config/nvim/init.lua ` and nothing showed up.
Also there's no commands starting with `:Wakatime`

Anything to fix this?

**Comment by fedemengo** [comment]
Once it's installed it should ask for the api key in the command bar and then you should be good to go
