### ISSUE TITLE
WakaTime heart beat is slow

### ISSUE THREAD

**Issue by YuseiUeno** [wakatime/vim-wakatime#153]
Is it possible change trigger event from CursorMoved to CursorHold?
Also, does it work without problems?

https://github.com/wakatime/vim-wakatime/blob/b487cccc0e920e4fdf84f72d2fc1c86ef8dc3bdc/plugin/wakatime.vim#L983

If it work, then I wanna replace CursorMoved event with User event for custumizable by user

**Comment by alanhamlett** [comment]
Looks like [CursorHold and CursorHoldI](https://vimdoc.sourceforge.net/htmldoc/autocmd.html#CursorHold) works and probably will make things faster.

Implemented with 413e9c4e44baaeb60beded33e26c37d9d22130b0.

**Comment by alanhamlett** [comment]
If you're noticing slowness sending heartbeats, make sure you have `debug = false` in your `~/.wakatime.cfg` file, or run this command inside Vim:

`:WakaTimeDebugDisable`

If debug mode was enabled, it will block the Vim UI until the heartbeat response is received from the WakaTime API.

**Comment by YuseiUeno** [comment]
It solved for me
Thank you for your help :)
