### ISSUE TITLE
Can't open file install_cli.py

### ISSUE THREAD

**Issue by jinreal** [wakatime/vim-wakatime#154]
I'm installing the plugin to gvim in Windows 8.1, I'm using vim-plug, and my gvim is installed in "D:\ide\gvim", it says the following:

```
[WakaTime] error installing wakatime-cli: python3w: can't open file 'D:\\C\\Users\\JinReal\\vimfiles\\plugged\\vim-wakatime\\scripts\\install_cli.py': [Errno 2]
 No such file or directory
```

Seems that it prepends the drive letter "D:"(the drive where my gvim is installed) to the script path unexpectedly.

**Comment by alanhamlett** [comment]
What's the output show when adding this line to your `~/.wakatime.cfg` file:

`debug = true`

**Comment by jinreal** [comment]
For clarity the window showing the install_cli.py opening error is called **Window 1**.

I notice that a new window(**Window 2**) popped up and then closed immediately, I can't copy the text without changing the install scripts, so I take a screenshot:
https://imgur.com/a/7stIYtA

Basically it says there's an error when processing command line, it looks like a problem with ssl library, so I install the cryptography and pyopenssl package and run gvim again, then **Window 2** popped up again(and disappears as before)showing the same text as the image above, but the text in **Window 1** changed to: 

```
[WakaTime] error installing wakatime-cli: [WakaTime Install] Current wakatime-cl
i version is v1.62.1
[WakaTime Install] Checking for updates to wakatime-cli...
[WakaTime Install] GitHub API Response 304
[WakaTime Install] wakatime-cli is up to date.
```

**Comment by jinreal** [comment]
Thanks, it seems that wakatime is running in background, and some new errors:

```
Error detected while processing BufEnter Autocommands for "*"..function <SNR>35_InitAndHandleActivity[4]..<SNR>35_HandleActivity[10]..<SNR>35_AppendHeartbeat[21]..<SNR>35_SendHeartbeats:
line  121:
[WakaTime] Command: "C:/Users/JinReal/.wakatime/wakatime-cli.exe" "--entity" "S:\tmp\test.txt" "--time" "1675290801" "--plugin" "vim/900 vim-wakatime/10.0.0" "--alternate-language" "text"^@[WakaTime] Error: '"C:/Users/JinReal/.wakatime/w
akatime-cli.exe"' is not recognized as an internal or external command,^@operable program or batch file.^@

```

Wierd that there's only wakatime-cli-windows-amd64.exe under ~/.wakatime, no other executables.

**Comment by alanhamlett** [comment]
The install script should have created a symlink, or copied `wakatime-cli-windows-amd64.exe` if symlinks aren't supported, to `~/.wakatime/wakatime-cli.exe`. If you copy it manually then it should fix the plugin... just not sure why the install script didn't do that.

**Comment by jinreal** [comment]
I copied it and it works now, thanks.
