### ISSUE TITLE
Plugin installed with lazyvim; dashboard doesnt update.

### ISSUE THREAD

**Issue by Xanthus58** [wakatime/vim-wakatime#156]
OS: Windows 10
Nvim Version: v0.8.2
Wakatime Version: v1.66.0
Debug Logs: https://pastebin.com/bbT5pLFN
Nvim Configs: https://github.com/Xanthus58/dotfiles/tree/main/.config/nvim

I've got the wakatime plugin installed; with the correct api key tied with my account. It works perfectly fine on vscode but the neovim version doesn't seem to work properly. If i run :WakaTimeToday i get this output 
![image](https://user-images.githubusercontent.com/66909997/220056097-58362a91-a0d1-4c28-a396-ba23f045b6bf.png)

I'm not entirely sure what else I can send over that may or may not help. So, if you need any further information, I'll be more than happy to provide it for you.

**Comment by alanhamlett** [comment]
That's two separate issues:

* the `:WakaTimeToday` bug is fixed with 62113bb063aa1923146e59270d71563441ceabe5, and should work after you update the plugin.
* the missing time, we need more info. Are there any errors in your `~/.wakatime.log` file? If not, enable debug mode and check again `:WakaTimeDebugEnable`.

**Comment by Xanthus58** [comment]
After the update everything seems to check out and work fine; the previous debug logs where in the Pastebin link I attached. As for now due to the issue being solved, I'll go ahead and close the issue. Thank you for your assistance.

**Comment by alanhamlett** [comment]
> the previous debug logs where in the Pastebin link I attached.

Oh sorry, I didn't see that. The only error there that looks like a bug is:
`{"caller":"cmd/params/params.go:401","func":"params.LoadHeartbeatParams","level":"error","message":"failed to read extra heartbeats: failed parsing: failed to json decode from data \"[{\\\"entity\\\": \\\"C:\\\\Users\\\\pikac\\\\AppData\\\\Local\\\\nvim\\\\lua\\\\plugins\\\\termdebug.lua\\\", \\\"timestamp\\\": 1676881606, \\\"is_write\\\": true, \\\"alternate_language\\\": \\\"lua\\\"}]\\n\": invalid character 'U' in string escape code","now":"2023-02-20T18:56:46+10:30","os/arch":"windows/amd64","version":"v1.66.0"}`

That looks like https://github.com/wakatime/wakatime-cli/pull/797, so it must not be fixed correctly.

**Comment by Xanthus58** [comment]
No worries at all; glad i could help out at least a little with helping to identify an issue.

**Comment by alanhamlett** [comment]
@Zephira58 can you check if it's fixed now?

**Comment by alanhamlett** [comment]
@Zephira58 can you check if this is fixed after updating the plugin in your nvim?
