### ISSUE TITLE
Coding stats not reported when API key is specified with "waka_"

### ISSUE THREAD

**Issue by resuni** [wakatime/vim-wakatime#157]
I noticed one of my computers wasn't reporting my coding stats. When I pulled up .wakatime.cfg, the only difference between the configs was that my `api_key` did not start with "waka_". I removed the "waka_" from the API key on the computer that wasn't working, and it started working. 

Using NeoVim with vim-plug. I tried enabling debug logs to see if it would report any errors when "waka_" was specified, but it does not. 

I'm okay with this workaround, but I thought I'd report the issue for others having this problem.

**Comment by alanhamlett** [comment]
What version of vim-wakatime are you using on that computer? It should support the `waka_` prefix if it's the latest version.

**Comment by resuni** [comment]
`nvim +PlugUpdate` reports that the plugin is the latest version. 

`$ .wakatime/wakatime-cli --version` returns: `v1.68.1`

I'm noticing this is very different from the "10.0.0" listed in the releases of this repo. I tried removing the plugin with `PlugClean` and reinstalling, but the version did not change.

**Comment by resuni** [comment]
I just found the [Plugin Status](https://wakatime.com/plugins/status) page, which reports "Version: 10.0.0 with cli 1.68.1 last seen 1 hour ago", so it does look like I'm using the latest version.

**Comment by alanhamlett** [comment]
When adding back the `waka_` prefix does it still work?

**Comment by resuni** [comment]
I just put it back and it seems to be working now. Weird.

**Comment by alanhamlett** [comment]
Yea, I think it was something unrelated to the api key prefix. The most likely cause was a temporary networking issue, which wouldn't show up in logs as long as the data was saved to the local db for syncing up later.
