### ISSUE TITLE
Move data file into wakatime folder

### ISSUE THREAD

**Issue by bnoctis** [wakatime/vim-wakatime#158]
There's `$HOME/.wakatime.bdb`.
There's `$HOME/.wakatime.cfg`.
There's `$HOME/.wakatime.data`.
There's `$HOME/.wakatime.log`.
There's `$HOME/.wakatime-internal.cfg`.

And there's `$HOME/.wakatime/`.

And, quote, "`$WAKATIME_HOME` defaults to your `$HOME` folder."

Why? Just, why?

I won't even bother talking about XDG because you most certainly don't know what that is. Just, put them in one directory. Pull yourself together.

**Comment by alanhamlett** [comment]
It crept up on us. We'll move the vim-specific `$HOME/.wakatime.data` file to `~/.wakatime/wakatime.data` and we have an issue open to track moving the other files with https://github.com/wakatime/wakatime-cli/issues/558.

**Comment by alanhamlett** [comment]
Actually, we already moved `$HOME/.wakatime.data` into `$HOME/.wakatime/` so you can delete `$HOME/.wakatime.data`.
