### ISSUE TITLE
Wakatime stopped working after cli update

### ISSUE THREAD

**Issue by Anemolo** [wakatime/vim-wakatime#160]
Hello, I've received an email that my wakatime wasn't working on my neovim! Not sure why but I suspect it's after some CLI update. But here's what I've found

My API key seems to be correct, I've even reset the key and changed it, same issue. 
I've also uninstalled and installed the package aswell

However, WakatimeDebugEnable throws:
```
Error detected while processing function <SNR>48_NeovimAsyncE
xitHandler:
line    6:
[WakaTime] Error 104: Invalid API Key
```

My Wakatime.cfg
```
[settings]
api_url = https://wakapi.dev/api
api_key=
# api_key=Some_old_api_key
debug=true
vi_redraw=enabled
api_key=the_new_and_correct_api_key
```

Manually doing ~/.wakatime/wakatime-cli --version outputs: 1.73.0
While the plugin status page shows as if I have 1.68

Also Running :WakatimeCliVersion throws this weird error:

:WakatimeCliVersion
```
Error detected while processing function WakaTimeCliVersion:
line   25:
E700: Unknown function: s:NeovimAsyncVersionOutputHandler
E700: Unknown function: s:NeovimAsyncVersionOutputHandler
line   33:
E6000: Argument is not a function or function name
```

**Comment by alanhamlett** [comment]
You have a custom `api_url` defined, so your data is going to that url not to WakaTime. You can setup heartbeat forwarding in your WakaApi settings or delete `api_url` from your cfg.

**Comment by alanhamlett** [comment]
Fixed `Error detected while processing function WakaTimeCliVersion` with 02be9238319937e04afea73fd0fc7da5413ee041.
