### ISSUE TITLE
avoid downloading wakatime-cli 

### ISSUE THREAD

**Issue by NotAShelf** [wakatime/vim-wakatime#161]
G'day, I intend to use vim-wakatime inside a Neovim configuration that is managed by the Nix package manager. However nix, if configured, builds packages inside a [sandbox](https://nixos.wiki/wiki/Nix_package_manager#Sandboxing) that does not have explicit network access - which means we cannot fetch wakatime-cli imperatively.

Would it be possible to have an option that determines whether or not the download is done, assuming the user can download wakatime-cli on their own?

**Comment by alanhamlett** [comment]
Setting `g:wakatime_CLIPath` turns off downloading/updating wakatime-cli.

**Comment by alanhamlett** [comment]
It needs to be set to the full path of the `wakatime-cli` binary.
