### ISSUE TITLE
Reported times seems invalid

### ISSUE THREAD

**Issue by Sigmanificient** [wakatime/vim-wakatime#165]
Hi, after spending an hour of setting up some nix derivation within nvim, 
I got a total time of 8 mins on the wakatime leaderboard.

It's been a week or so since i moved to vim, and from that point, my average time have been shrinking quite a bit.
After further investigation i noticed that my times on nvim are often reported as 0 mins, goes rarely beyond a few minutes. 

I'm not sure what is happening, and i could not find any problems within my `~/.wakatime.log`

Are the hearbeat send only within the insert mode if it going beyond a minute?
Could it came from lazy nvim package manager?

**Comment by alanhamlett** [comment]
When using [lazy.nvim](https://github.com/folke/lazy.nvim) package manager with `lazy` set to `true`, it says plugins won't be loaded on startup. That means vim-wakatime might not be loaded, so it won't be able to track your Nvim usage. Try disabling `lazy` and see if it starts working?

**Comment by 50-Course** [comment]
Conversely, I found out it lags for a while too here, reports incorrect log hours on the Vim integration but logs correct work hours on the dashboard. Then after a while, updates at the next check with old log hours.

**Comment by alanhamlett** [comment]
Also check if it's related to the way leaderboard stats are calculated differently than dashboard stats:

https://wakatime.com/faq#leaderboard-vs-dashboard
