### ISSUE TITLE
Not creating symlink from wakatime-cli.exe to wakatime-cli-windows-386.exe

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vim-wakatime#166]
Now I have the same issue, but I have "wakatime-cli-windows-386.exe" instead of "wakatime-cli-windows-amd64.exe".
Like this:
![image](https://github.com/wakatime/vim-wakatime/assets/37146904/48cd43b6-3534-44aa-932c-f938162e76c5)

If i rename the "wakatime-cli-windows-386.exe" file to "wakatime-cli.exe", when i restart nvim, it will be removed.

_Originally posted by @ParadiseWitch in https://github.com/wakatime/vim-wakatime/issues/147#issuecomment-1678314437_

**Comment by alanhamlett** [comment]
@ParadiseWitch you're using 32bit Windows? On startup, vim-wakatime should download one of [these releases](https://github.com/wakatime/wakatime-cli/releases/tag/v1.74.1) corresponding to your OS, then create a symlink from `~/.wakatime/wakatime-cli.exe` to `~/.wakatime/wakatime-cli-windows-386.exe`. If the symlink fails, vim-wakatime tries moving the file to `~/.wakatime/wakatime-cli.exe` instead.

**Comment by ParadiseWitch** [comment]
@alanhamlett No, 64bit.
![image](https://github.com/wakatime/vim-wakatime/assets/37146904/94c575b8-89d0-4182-be33-952c81448eb6)

**Comment by alanhamlett** [comment]
That's the problem... it's downloading 32-bit wakatime-cli and then it fails checking the current version with `wakatime-cli.exe --version`. If we fix 32/64 bit detection then it should start working.

**Comment by alanhamlett** [comment]
Closing as fixed because no response.

**Comment by alanhamlett** [comment]
Also added ba4537e36a81f1eb25d511d40eb59e0bb1acff87 to help with this issue.
