### ISSUE TITLE
Not Showing on my dashboard

### ISSUE THREAD

**Issue by FkLalita** [wakatime/vim-wakatime#170]
i can't see my time on the dashboard but i can see my time on vscode on it, i check the logs but i can't seem to find any error related to vim, but i can see numbers on my vim_shared_state which changes if i code, i assumed that is my code time, but it is not showing on my dashboard, if i try WakaTimeToday or the other cmd i get wakatime-cli is not recognised as an internal or external command.

**Comment by alanhamlett** [comment]
> i can't see my time on the dashboard but i can see my time on vscode on it

Your dashboard is missing vim stats, but has vscode stats?


> if i try WakaTimeToday or the other cmd i get wakatime-cli is not recognised as an internal or external command.

Sounds like vim-wakatime plugin can't find `~/.wakatime/wakatime-cli`. Can you make sure it's in that location?

**Comment by FkLalita** [comment]
Yes, I have the wakatime-cli.exe on the .wakatime folder.

Yes![Screenshot_20231016-194756.png](https://github.com/wakatime/vim-wakatime/assets/109562469/fe18ca9b-bf82-4d2f-b902-934bcfb6607f)

**Comment by alanhamlett** [comment]
Ok, please enable debug mode with `:WakaTimeDebugEnable` then share the error message printed at the bottom of your Vim after editing a file inside Vim.

**Comment by FkLalita** [comment]
[C:\Users\DSRC\Desktop\Go\hello\now.go] [Location List] [-]                                                                        [dos]  28% ㏑:10/35☰℅:51
Error detected while processing BufEnter Autocommands for "*"..function <SNR>60_InitAndHandleActivity[4]..<SNR>60_HandleActivity[10]..<SNR>60_AppendHeartbeat
[21]..<SNR>60_SendHeartbeats:
line  121:
[WakaTime] Command: "C:/Users/DSRC/.wakatime/wakatime-cli.exe" "--entity" "C:\Users\DSRC\Desktop\Go\hello\now.go" "--time" "1697498160" "--plugin" "vim/900 v
im-wakatime/11.0.0" "--alternate-language" "go"^@[WakaTime] Error: '"C:/Users/DSRC/.wakatime/wakatime-cli.exe"' is not recognized as an internal or external
command,^@operable program or batch file.^@

**Comment by alanhamlett** [comment]
And if you relaunch vim?

**Comment by FkLalita** [comment]
Yes, a lot of time

**Comment by FkLalita** [comment]
I relaunch vim but it is not working

**Comment by alanhamlett** [comment]
With debug enabled you should see some logs printed when Vim first starts. When it's working it should print:

```
[WakaTime] error installing wakatime-cli: [WakaTime Install] Current wakatime-cli version is v1.85.2
[WakaTime Install] Checking for updates to wakatime-cli...
[WakaTime Install] GitHub API Response 304
[WakaTime Install] wakatime-cli is up to date.
Press ENTER or type command to continue
```

But there might be an error message telling us why it's not able to execute `C:/Users/DSRC/.wakatime/wakatime-cli.exe` on your machine.

**Comment by FkLalita** [comment]
So I find the error though, I think vim is looking for wakatime-cli.exe but I have wakatime-windows-386-cli.exe, so I renamed to wakatime-cli.exe and I no longer see the error but vscode keep showing wakatime error, so I copy the wakatime-cli.exe and rename it to the default one, so both are working fine I guess, I can now see vim on my dashboard.............. though it is showing unknown project for vim I guess it has to do with my file path.....but I can now see vim on my dashboard 😌

**Comment by FkLalita** [comment]
i keep getting unknown project on my dashboard anytime i use vim though

**Comment by alanhamlett** [comment]
Are you using a Git repo for your project?

**Comment by FkLalita** [comment]
No

**Comment by FkLalita** [comment]
No

**Comment by alanhamlett** [comment]
Without a Git repo the plugin has no way to detect a project. Please set a project using one of the [supported methods](https://wakatime.com/faq#create-projects).

**Comment by alanhamlett** [comment]
There's other ways besides Git. Please read the FAQ link.
