### ISSUE TITLE
Always `Invalid api key format` in LunarVim,but works fine with VSCode

### ISSUE THREAD

**Issue by WendaoLee** [wakatime/vim-wakatime#173]
I'm working on `LunarVim`,it's just a layer of neovim.But it seems like it cannot correctly read the api-key.I have tried reset api-key for many times,but it still not work.

But the wakatime plugins works well in the VSCode:
<img width="91" alt="image" src="https://github.com/wakatime/vim-wakatime/assets/39958730/84c5c911-9465-49a6-84af-4fd4976ac2e0">

Could you please give me any advice to fix that?

wakatime.log:
```log
{"caller":"cmd/run.go:270","func":"cmd.runCmd","level":"error","message":"failed to run command: today fetch failed: failed to load API parameters: invalid api key format","now":"2023-12-08T22:07:24+08:00","version":"v1.54.0"}
{"caller":"cmd/params/params.go:362","func":"params.LoadHeartbeatParams","level":"error","message":"failed to read extra heartbeats: failed to json decode: failed to json decode from data \"[{\\\"entity\\\": \\\"G:\\\\Github\\\\wendaolee.github.io\\\\ci\\\\app\\\\Main.hs\\\", \\\"timestamp\\\": 1702044444, \\\"is_write\\\": false, \\\"alternate_language\\\": \\\"haskell\\\"}]\\n\": invalid character 'G' in string escape code","now":"2023-12-08T22:07:49+08:00","version":"v1.54.0"}
```

**Comment by shadmeoli** [comment]
@WendaoLee  Are you using lunar with packer or mason?

**Comment by WendaoLee** [comment]
> @WendaoLee Are you using lunar with packer or mason?

Nope,I'm using [lazy.nvim](https://github.com/folke/lazy.nvim).

**Comment by shadmeoli** [comment]
With [this PR](https://github.com/wakatime/vim-wakatime/pull/179) it should work. I had the same issue - I had to set it up manually and it worked. You can follow the guide also [here](https://github.com/shadmeoli/nvim_wakatime_setup).

**Comment by WendaoLee** [comment]
> With [this PR](https://github.com/wakatime/vim-wakatime/pull/179) it should work. I had the same issue - I had to set it up manually and it worked. You can follow the guide also [here](https://github.com/shadmeoli/nvim_wakatime_setup).

ty,I would try it when I back home.❤️

**Comment by alanhamlett** [comment]
Also updated install instructions for lazy-vim here:
https://wakatime.com/vim#lazyvim-install
