### ISSUE TITLE
Neovim is showing as Vim

### ISSUE THREAD

**Issue by hougesen** [wakatime/vim-wakatime#175]
For the last couple of days my Neovim usage has been tracked as Vim.

I am using Lazy.nvim as package manager with the following setup:

```lua
local plugins = {
  'wakatime/vim-wakatime',
  -- ...
}
```

According to the Wakatime plugin status page, Neovim was last seen on December the 6th. So I am guessing it is related to 8c8856327815a077cbebeba8c7456312a3d2c39c.

It doesn't really have any effect on me, just thought you guys should know in case it isn't on purpose 😄

My Wakatime username is [@hougesen](https://wakatime.com/@hougesen)

**Comment by wyatt-avilla** [comment]
I'm getting the same behavior, and I'm using Packer. I was able to recreate it in a fresh VM with Wakatime being the only plugin installed.

**Comment by alanhamlett** [comment]
Fixed server-side.
