### ISSUE TITLE
Can't set Vim-Wakatime on Neovim at Debian on WSL 2

### ISSUE THREAD

**Issue by laporeon** [wakatime/vim-wakatime#177]
Hi, I'm using Debian 12 on WSL, on a Windows 10 environment. 

`OS: Debian GNU/Linux 12 (bookworm) on Windows 10 x86_64`

I've installed vim-wakatime plugin and, after I reboot neovim, the following message shows up:
![image](https://github.com/wakatime/vim-wakatime/assets/34722707/280d54e3-2a12-43f6-9d22-5e73f5de2fbf)

I did some research and downloaded the file and unziped on `.wakatime` folder, reboot neovim but the message is still there. I did another research and someone suggested to reinstall the plugin. I did that as well, always reminding to reboot neovim after every small change. But the message is still there... I have the same configuration on Ubuntu 22.04, also on WSL on the same laptop and this "error" never appeared.

This is the current content of the folder on Debian. I don't know what else to do. Can anyone help me, please?
![image](https://github.com/wakatime/vim-wakatime/assets/34722707/dd3bbb3e-6ece-4d53-8ee9-b8a33239da14)

**Comment by alanhamlett** [comment]
What's the contents of the `~/.wakatime/` folder on WSL?

**Comment by laporeon** [comment]
It's on the last image uploaded

**Comment by shadmeoli** [comment]
This should fix the issue [#179](https://github.com/wakatime/vim-wakatime/pull/179). 
> If you are using Lazy.

**Comment by laporeon** [comment]
> This should fix the issue [#179](https://github.com/wakatime/vim-wakatime/pull/179).
> 
> > If you are using Lazy.

Thanks, but unfortunately i'm using Vim-Plug and I don't plan to change at this moment.

**Comment by laporeon** [comment]
Still couldn't get rid of this error. Would appreciate any other help.

**Comment by alanhamlett** [comment]
What's the output of the vim command:

`:WakaTimeCliLocation`

**Comment by laporeon** [comment]
![image](https://github.com/wakatime/vim-wakatime/assets/34722707/476f7a1a-d09c-48c1-a58b-ca8edf5dac28)

Here

**Comment by alanhamlett** [comment]
You can rename `wakatime-cli-linux-amd64` to `wakatime-cli` and it should work.

**Comment by laporeon** [comment]
I did that about half hour ago and the message disappeared, but the time doesn't seem to be counting though. My key is right, this is the current content of `.wakatime` folder after i renamed `wakatime-cli-linux-amd64` to `wakatime-cli`: 

![image](https://github.com/wakatime/vim-wakatime/assets/34722707/c06dc2b7-c5d3-4fe3-8cf1-c0cc82702c8d)

When i run `:WakaTimeToday` or `:WakaTimeCliVersion` get this error:
![image](https://github.com/wakatime/vim-wakatime/assets/34722707/6d16ae61-983b-4f81-b93c-054e285c84f9)

and this other error appears few seconds later:

![image](https://github.com/wakatime/vim-wakatime/assets/34722707/65aaf385-77f4-4cb1-94e1-e5293d520eda)

What am I doing wrong? I had the same plugin installed on Ubuntu 22.04 on WSL environment and all it took was follow theses steps according to the plugin manager i am using:

![image](https://github.com/wakatime/vim-wakatime/assets/34722707/60489995-69ce-4ed4-8b2a-561688bc5a78)

**Comment by alanhamlett** [comment]
Try `chmod a+rx wakatime-cli`?

I don't know much about WSL, but if it's really running Debian then a permission error should be fixed with chmod.

**Comment by laporeon** [comment]
Thanks, chmod command worked and now I can use `:WakaTimeToday` and `:WakaTimeCliVersion`, but still with some strange behavior. 

I'm not gonna close the issue right now and i'll give it a day or two to check if it's going to work as it should.

Thank you for your help and i'll come back with more data soon.

**Comment by laporeon** [comment]
After testing for about 4 hours, i found out vim-wakatime plugin on Neovim is, indeed, not working as it should. It is counting time, but it's not recognizing the project's name. 

Using the same project, I coded for 2 straight hours on Neovim and went to VS Code for another 2 hours session. For Neovim, the dashboard displays "unknow project" as for VS Code, the project's name is properly displayed. This was not happening while I was using Neovim on a Ubuntu 22.04 envinroment. 

I'm gonna leave this issue open for a few more days just to see if anyone can help me. If not, i will simply uninstall it and move on. It's been quite a journey to make it work on Debian and still no success. But i'd appreciate your help anyways.

**Comment by alanhamlett** [comment]
Which project detection method is your project using?

**Comment by laporeon** [comment]
Sorry, I read that but still couldn't understand.

Don't know if this helps, but mostly I just create an empty folder via terminal using default `mkdir <folder>` command, and then open it either using `code <folder>` ou `nvim <folder>`. This always worked, even if it wasn't a Git repository.

This projecty, for instance, was created like this. It doesn't even have a .git folder because i didn't initiated a repository whatsoever

**Comment by alanhamlett** [comment]
That works because vscode has the concept of projects when you open a folder, and WakaTime uses that as the backup project name. Vim can't open folders as projects, so you need to first run this command in the folder to get it working in nvim:

```
cd <folder>
git init
```

**Comment by laporeon** [comment]
Hm. Ok, didn't know that. 

I'm gonna close the issue now since it's been resolved. Thank you for your time.
