### ISSUE TITLE
Used 'python_bin' should be configurable from vimrc

### ISSUE THREAD

**Issue by mclang** [wakatime/vim-wakatime#18]
Problem is that CentOS 5 has very old python (2.4) and wakatime doesn't work with it. I have installed newer python versions in 'usr/local' as alternate versions, meaning that their binaries are named like python2.7 and python3.4, but I don't have good way to tell wakatime to use those instead the default 'python' one.

Thus the 'python_bin' variable in wakatime.vim should be made accessible from users vimrc.

**Comment by alanhamlett** [comment]
Added with d639c5ea7bbd67e5a3b4974a982f6c4412f4aa31.

More info at https://github.com/wakatime/vim-wakatime#configuring
