### ISSUE TITLE
Warn about missing api key instead of blocking IO

### ISSUE THREAD

**Issue by fedemengo** [wakatime/vim-wakatime#181]
With a fresh neovim setup, during plugins installation it's really annoying to have the process blocked by wakatime asking for the api key. 

In my opinion it would be much better to just warn about the missing key and keep wakatime disable for the time being. Most of the plugins simply log errors/info rather than launching blocking procedures. At least it would be useful to provide an option to just log the error

**Comment by alanhamlett** [comment]
Fixed with 4faeea55c895b9f2d27ea1db68a68780b2e4585b.
