### ISSUE TITLE
WARNING {vim-wakatime}: unknown key <setup>

### ISSUE THREAD

**Issue by alexventuraio** [wakatime/vim-wakatime#182]
I recently started configuring NeoVim for my Mac computer and added the waka-time plugin as stated in the README file.
This is my plugin config:
```viml
return {
  'wakatime/vim-wakatime',
  lazy = false,
  setup = function()
    vim.cmd([[ packadd wakatime/vim-wakatime ]])
  end,
}
```
I get stats reflected in my dashboard so I think it is ok but I get this warning when running `checkhealth`. I think it has to do with this line from the code above `setup = function()`:
```shell
- WARNING {vim-wakatime}: unknown key <setup>
```
<img width="586" alt="Screenshot 2024-02-25 at 22 27 08" src="https://github.com/wakatime/vim-wakatime/assets/13169164/ac333e42-a53e-418e-8dbc-0fff0ca3bbc8">

Not sure how to fix it, I tried changing with `config = function()` but that errors out.
Does anyone know whether or not it is an issue that should be fixed?

**Comment by alanhamlett** [comment]
You can just remove `setup` and change the config to:
`{ 'wakatime/vim-wakatime', lazy = false }`

That seems to work fine in lazy-vim.


Fixed with 56b4d073adaf18c04c7bb5728d41c03b2f25754d.
