### ISSUE TITLE
[Windows 10] Invalid value for argument cmd .wakatime/wakatime-cli.exe

### ISSUE THREAD

**Issue by AngelaVilladiego** [wakatime/vim-wakatime#183]
I have NeoVim installed and running on an up-to-date Windows 10 system. I am using Packer for my package manager. Upon adding the line `use("wakatime/vim-wakatime")` and running a :PackerSync, wakatime is installed in NeoVim, however I get the following error:

`Error detected while processing CursorHold Autocommands for "*"..function <SNR>40_HandleActivity[23]..<SNR>40_SendHeartbeats:
line   71:
E475: Invalid value for argument cmd: 'C:/Users/<user>/.wakatime/wakatime-cli.exe' is not executable`

I get a similar error when running any of the other Wakatime commands within nvim.

I went to the path listed in the error and found that I do not have `wakatime-cli.exe`, but I do have `wakatime-cli-windows-amd64.exe`. My Wakatime plugin works for Visual Studio and Visual Studio Code, so I wonder if this executable's name is switched on Windows and the Neovim plugin doesn't look for this name by default. I couldn't figure out how to change it after reading the documentation or what to do to make it work.

How can this be resolved?

**Comment by alanhamlett** [comment]
The plugin should have symlinked or renamed `wakatime-cli-windows-amd64.exe` to `wakatime-cli.exe`, but you can fix it by doing it manually.
