### ISSUE TITLE
*request* ability to report seperate neovim configs as seperate editors?

### ISSUE THREAD

**Issue by thederpykrafter** [wakatime/vim-wakatime#186]
I'm not sure if this is already possible, but I often switch between my NeoVim and LunarVim configs. currently both show as NeoVim on wakatime. Is it possible to isolate each to their own stats?

**Comment by alanhamlett** [comment]
Do they have different plugin directories or share the same plugin folder?

If they're different, you could edit the `plugin/wakatime.vim` file in you LunarVim plugin folder to hard-code it to `LunarVim` when passing the `--plugin` argument to `wakatime-cli`.

**Comment by thederpykrafter** [comment]
To be honest I'm relatively new to neovim as a whole. At this point I'm not even sure how this plugin is working in my lunarvim config because lazy doesn't show the plugin at all despite all WakaTime commands working. Lunarvim just uses powershell aliases to launch neovim I think. I might just merge my configs into one like I should have to begin with lol

**Comment by alanhamlett** [comment]
Closing for now. One way to do this already is using a different `$WAKATIME_HOME` env var in Neovim.
