### ISSUE TITLE
Feature request: ignore missing api key

### ISSUE THREAD

**Issue by xzfc** [wakatime/vim-wakatime#187]
I am using the same neovim configuration across multiple machines. Some of them have `~/.wakatime` configured, and some of them don't. On machines without wakatime configured, `vim-wakatime` emits the following warnings on vim open and periodically every few minutes, which is annoying.
```
Error detected while processing BufEnter Autocommands for "*"..function <SNR>8_InitAndHandleActivity[2]..<SNR>8_SetupConfigFile:
line   22:
[WakaTime] Type the Vim command :WakaTimeApiKey to enter your WakaTime API Key. Find yours at https://wakatime.com/api-key
Press ENTER or type command to continue
```

```
Error detected while processing function <SNR>8_NeovimAsyncExitHandler:
line    6:
[WakaTime] Error 104: Invalid API Key
Press ENTER or type command to continue
```

It would be convenient, if these message be less annoying. Some suggestions:
- Use `echomsg` instead of `echoerr` so the editor won't get blocked waiting for user input.
- Don't auto-emit "missing key/config" diagnostics unless asked to. E.g. provide a `WakaTimeStatus` command. For `neovim` you could use the [Healthcheck framework](https://neovim.io/doc/user/pi_health.html).
- If API key is not provided, disable the plugin, so "Invalid API Key" won't get emitted every few minutes.

I believe that merely installing the plugin shouldn't force the user to use it.

**Comment by alanhamlett** [comment]
Fixed with 53bba6bb8342de9cbdafc82142a9b5e82008d858.
