### ISSUE TITLE
23,893+ heartbeats created while using nvim (iTerm2)

### ISSUE THREAD

**Issue by alexreyes** [wakatime/vim-wakatime#188]
Hi, I followed the [instructions](https://wakatime.com/terminal) for using wakatime with iTerm2, and I started using nvim on iterm2 for a couple of minutes.

Within ~30 min, there were 20k+ events created on wakatime. For a while when I would refresh the heartbeats page it kept going up, but after disabling the trigger it stopped.

<img width="679" alt="Screenshot 2024-08-26 at 3 55 49 PM" src="https://github.com/user-attachments/assets/07d60665-90ce-4113-bd84-4ca394e65eb0">

I'm not sure why this happened. I did not have `Instant` enabled. Sorry for potentially DDOS-ing wakatime!

**Comment by alanhamlett** [comment]
Yes, please use the vim-wakatime plugin but not the iTerm2 trigger. I've updated the website to remove iTerm2 install instructions.

**Comment by alexreyes** [comment]
Okay I just installed vim wakatime instead, thanks!
