### ISSUE TITLE
fix: lazy.nvim links

### ISSUE THREAD

**Issue by Rewwoken** [wakatime/vim-wakatime#189]
Hi!

I haven't found the website repo, so issuing here.
There are broken links on [wakatime.com/neovim](https://wakatime.com/neovim) for [lazy.nvim](https://wakatime.com/neovim#lazyvim-install):

1. Install [lazy.nvim](https://github.com/folke/lazy.nvim?tab=readme-ov-file#-installation) for NeoVim. => 1. Install [lazy.nvim](https://lazy.folke.io/installation) for NeoVim.

2. Add this line to your [plugins.lua](https://github.com/folke/lazy.nvim?tab=readme-ov-file#-structuring-your-plugins) => 2. Add this to your [plugins](https://lazy.folke.io/spec/examples)

Hope this helps! Thanks for your time.

**Comment by alanhamlett** [comment]
Fixed, thanks!
