### ISSUE TITLE
Report 'language' based on the vim filetype of the active buffer

### ISSUE THREAD

**Issue by lepht** [wakatime/vim-wakatime#19]
Not sure if the wakatime API supports specifying the language on the client side, but it'd be kind of nice to take advantage of the fact that vim knows the language/filetype to intelligently set the language on wakatime. This would be helpful to avoid constantly setting up filters to set language on wakatime.

**Comment by alanhamlett** [comment]
We use [Pygments](http://pygments.org/languages/) to detect the language in the [wakatime-cli](https://github.com/wakatime/wakatime/blob/67c5f02a8085c4aa5d3af03e50066e70142ddadc/wakatime/stats.py#L49) client. It supports more languages than Vim but we could send the filetype from Vim as a suggestion for when Pygments can't detect a language.

Which languages are not being detected for you?

**Comment by lepht** [comment]
In particular its an issue for languages that need more context than just the file contents – an example is ansible files, where something like pygments will report yaml, but the ansible vim syntax knows (based on the path/standard ansible for structure) that it's specifically ansible.

**Comment by mfontani** [comment]
The following worked for me since pygments' `guess_lexer` actually checks the Vim modeline, whereas I believe `guess_lexer_for_filename` only checks the file extension.

This has bugged me so much that I had to "fix it".

```
--- a/plugin/packages/wakatime/stats.py
+++ b/plugin/packages/wakatime/stats.py
@@ -20,7 +20,7 @@ if sys.version_info[0] == 2:
     sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'packages', 'pygments_py2'))
 else:
     sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), 'packages', 'pygments_py3'))
-from pygments.lexers import guess_lexer_for_filename
+from pygments.lexers import guess_lexer


 log = logging.getLogger('WakaTime')
@@ -50,7 +50,7 @@ def guess_language(file_name):
     language, lexer = None, None
     try:
         with open(file_name, 'r', encoding='utf-8') as fh:
-            lexer = guess_lexer_for_filename(file_name, fh.read(512000))
+            lexer = guess_lexer(fh.read(512000))
     except:
         pass
     if file_name:
```

**Comment by alanhamlett** [comment]
@mfontani nice find.. i thought `guess_lexer_for_filename` called `guess_lexer` limited to file extensions, but looks like it's totally different and forgets the vim modeline check.

The latest version of vim-wakatime uses both guess functions and picks the lexer with the highest accuracy.
