### ISSUE TITLE
I have email from support@ about unusual coding activity

### ISSUE THREAD

**Issue by kalloc** [wakatime/vim-wakatime#190]
So, I have just installed [vim-ai](https://github.com/madox2/vim-ai) plugin, which uses a buffer for chat sessions.

--
```
:echo &filetype
aichat
:echo expand('%')
>>> AI chat
```

**Comment by kalloc** [comment]
I think we need to configure ignore list of filetypes

**Comment by gandarez** [comment]
Any unusual activity an email is sent but if you consider a regular activity you can reply to the same email and the support team will catch it.
