### ISSUE TITLE
not reporting logged time

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vim-wakatime#25]
Copied from http://www.reddit.com/r/WakaTime/comments/34xw7a/wakatime_for_vim_not_reporting/

> I've got the WakaTime plugin for vim set up, configured my API key, and have worked extensively for over a week in Vim, but it's not getting reported to WakaTime (or at least not showing up on my dashboard or elsewhere). My .wakatime.log file is empty. My .wakatime.data file shows the file I'm editing, but what I assume are a pair of timestamps are equal. My IntelliJ IDEA plugin works fine, but not Vim.
I do the vast majority of my work in Vim, so with out this, WakaTime isn't much good to me =(.

**Comment by alanhamlett** [comment]
Can you upgrade to the latest version of the plugin? Some others have had this issue and it's been fixed in the latest version.

**Comment by crdil** [comment]
I'm having trouble getting Wakatime to report for vim. I works with atom and sublime but not vim. I've installed the plugin and the api key is already set in .cfg file by atom. But still no reporting.. what could be the issue?
