### ISSUE TITLE
'%s' not expanded in log.warn() <-- "No module named configs"?

### ISSUE THREAD

**Issue by chiselwright** [wakatime/vim-wakatime#27]
I've just started using wakatime and the service itself works really well.

This morning I peeked at the logfile and noticed it wasn't particularly useful; it was full of lines like:

    {"now": "2015/05/30 10:14:50 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980890.122888, "level": "WARNING", "message": "%s"}

I've enabled debugging and done a few simple file actions (open, close, check log, ...).
This is the output from that:

    ➔ rm ~/.wakatime.log
    ➔ vim ~/.wakatime.cfg
    ➔ cat ~/.wakatime.log
    {"now": "2015/05/30 10:14:01 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980841.171594, "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py", "lineno": 99, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Traceback (most recent call last):\n  File \"/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py\", line 93, in __init__\n    module = import_module('.%s' % module_name, package=__package__)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\nImportError: No module named configs\n"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.  py", "lineno": 314, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Sending heartbeat to api at https://wakatime.com/api/v1/heartbeats"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 341, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": {"is_write": true, "lines": 9, "language": "INI", "file": "/home/chisel/.wakatime.cfg", "time": 1432980847.702621}}
    {"now": "2015/05/30 10:14:08 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/packages/requests/packages/urllib3/util/ssl_.py", "lineno": 79, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:08 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 391, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": {"response_code": 201}}
    ➔ vim ~/.wakatime.cfg
    ➔ cat ~/.wakatime.log
    {"now": "2015/05/30 10:14:01 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980841.171594, "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py", "lineno": 99, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Traceback (most recent call last):\n  File \"/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py\", line 93, in __init__\n    module = import_module('.%s' % module_name, package=__package__)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\nImportError: No module named configs\n"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 314, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Sending heartbeat to api at https://wakatime.com/api/v1/heartbeats"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 341, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": {"is_write": true, "lines": 9, "language": "INI", "file": "/home/chisel/.wakatime.cfg", "time": 1432980847.702621}}
    {"now": "2015/05/30 10:14:08 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/packages/requests/packages/urllib3/util/ssl_.py", "lineno": 79, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:08 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 391, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": {"response_code": 201}}
    {"now": "2015/05/30 10:14:29 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980868.548927, "level": "WARNING", "message": "%s"}
    ➔ vim ~/.wakatime.cfg
    ➔ vim ~/.wakatime.cfg
    ➔ vim ~/.wakatime.cfg
    ➔ tail ~/.wakatime.log
    {"now": "2015/05/30 10:14:01 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980841.171594, "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py", "lineno": 99, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Traceback (most recent call last):\n  File \"/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py\", line 93, in __init__\n    module = import_module('.%s' % module_name, package=__package__)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\nImportError: No module named configs\n"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 314, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Sending heartbeat to api at https://wakatime.com/api/v1/heartbeats"}
    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 341, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": {"is_write": true, "lines": 9, "language": "INI", "file": "/home/chisel/.wakatime.cfg", "time": 1432980847.702621}}
    {"now": "2015/05/30 10:14:08 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/packages/requests/packages/urllib3/util/ssl_.py", "lineno": 79, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:08 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/base.py", "lineno": 391, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": {"response_code": 201}}
    {"now": "2015/05/30 10:14:29 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980868.548927, "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:40 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980880.513787, "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:45 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980884.821277, "level": "WARNING", "message": "%s"}
    {"now": "2015/05/30 10:14:50 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980890.122888, "level": "WARNING", "message": "%s"}

I'm not familiar with python, so my attempts to debug, resolve and submit a pull-request failed.
Let me know if you require any further information.

The line that looks most interesting/useful to my un-python eyes is:

    {"now": "2015/05/30 10:14:07 +0000", "version": "4.0.13", "plugin": "vim/704 vim-wakatime/4.0.0", "time": 1432980847.702621, "caller": "/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py", "lineno": 99, "isWrite": true, "file": "/home/chisel/.wakatime.cfg", "level": "DEBUG", "message": "Traceback (most recent call last):\n  File \"/home/chisel/.vim/bundle/vim-wakatime/plugin/packages/wakatime/languages/__init__.py\", line 93, in __init__\n    module = import_module('.%s' % module_name, package=__package__)\n  File \"/usr/lib/python2.7/importlib/__init__.py\", line 37, in import_module\n    __import__(name)\nImportError: No module named configs\n"}

**Comment by alanhamlett** [comment]
The traceback is normal and nothing to be alarmed about. Some more info is here: wakatime/wakatime#22

The `201` api response means heartbeats are getting sent correctly, so everything should be working normal.

**Comment by chiselwright** [comment]
This was more about literal '%s' being logged instead of the message.
The 'configs' stacktrace might be a non/different issue, but it was a handy way to generate the 

    "level": "WARNING", "message": "%s"

example entries.

**Comment by alanhamlett** [comment]
Fixed the `%s` log message by upgrading wakatime cli to v4.0.14.
