### ISSUE TITLE
slow startup time on Windows OS

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vim-wakatime#28]
Ken says,

> 90% of the time it takes 5-7 seconds for for vim to start.  The other 10% of the time it takes over 7 seconds, more like 10-15

**Comment by kasajian** [comment]
I stopped using waka-time under VIM for Windows.   As of yesterday, I stopped using it on the Mac as well because of errors during usage.   I am thinking that may be waka-time support for vim isn't going to be something stable unfortunately.   Perhaps best to focus efforts elsewhere

**Comment by alanhamlett** [comment]
What do u mean by unstable? I also use Vim with WakaTime on OS X daily but it's stable for me. Do you have an error message?

**Comment by kasajian** [comment]
alan, I do get errors on the Mac.  I don't know why.   It would happen when I try to do a save on the file.  I get some gibberish lines, but it does save.   Still a little disconcerting.   When I see stuff like that, I just assume, "not ready for prime-time" and uninstall it.   I'll just wait a while until things stabilize.   On a good note, I haven't seen any problems with using wakatime on the Visual Studio side -- I use that about half the time

**Comment by alanhamlett** [comment]
Not able to debug this without an error message, so I'll close it for now.

**Comment by alanhamlett** [comment]
Oops. This was about slow startup time on Windows, not Mac errors. Reopening for original issue.

**Comment by charliewynn** [comment]
Just signed up, I probably spend 90% of my time in vim.  Have to say the slow startup is painfully noticeable already :/

**Comment by alanhamlett** [comment]
@charliewynn I'll try to reproduce this on Windows later tonight, but would you be able to help by commenting out various startup code from the plugin and restarting vim to see if the commented code was causing the slow startup? A comment in vim script is a quote character. The file to edit should be at <vimdir>\vundle\plugins\vim-wakatime\plugin\wakatime.vim

**Comment by charliewynn** [comment]
Yep, I should be able to handle any poking around in the .vim you want me to try :smile:

**Comment by charliewynn** [comment]
I'm using pathogen to manage the bundle.  Putting a ~ at the end of the vim-wakatime folder (so pathogen ignores it), vim opens in around one second.  With it un-edited (so vim-wakatime loads), it takes 7-15 seconds

wakatime.vim loads quickly, but the plugin folder inside vim-wakatime seems to be the culprit.  If I delete that vim loads quickly.
Maybe having the .py and .pyc adds to the startup time?

**Comment by alanhamlett** [comment]
Hmm, I'll check on my virtual machine but Vim shouldn't do anything with the .py or .pyc files except when vim-wakatime forks a python process to send a heartbeat. Maybe Vim is trying to send a heartbeat when starting up.

**Comment by charliewynn** [comment]
Maybe it's pathogen that's taking it's time reading through the .py/pyc files
If I comment out everything in the .vim it is still slow.
If I do the comment at the end of the vim-wakatime/plugin/packages it's still slow (I'm not sure if pathogen ignores ~ folders that are in sub-directories, or just the parent folders)
If I delete that folder it's fast.
wiping out the augroup doesn't help.  So I'm suspecting pathogen again.

---

I just copied vim-wakatime.vim and the packages folder to /autoload so pathogen wouldn't read through it.  Vim is fast to load again, doing some tests to see if it waka is still working with this

**Comment by alanhamlett** [comment]
As long as `wakatime.vim` is loaded and the packages folder is in the same directory as `wakatime.vim` that would work.

I don't see any code related to python files in Pathogen, but maybe just traversing all the sub-directories in the `plugin/packages` folder looking for `.vim` files is taking a long time?

**Comment by pntuananh** [comment]
Hi, I also have the slowness problem. I followed charliewynn's way that just copies vim-wakatime.vim and packages folder to /autoload, but the problem is still there. So how can I solve this? Thanks.

**Comment by alanhamlett** [comment]
If it's not slow because of Pathogen walking the wakatime Python folder, then it was probably slow because of forking a Python process to send a heartbeat when first opening a file. That problem has been fixed, so updating the plugin will speed up opening Vim.

**Comment by alanhamlett** [comment]
Closing since this may be fixed. Can reopen if it's still an issue.

**Comment by dohq** [comment]
Hi alan.
I'm sorry that my English isn't very good.

I using this plugin to vim on windows10.
but very very slowly vim to startup.

i testing this vimrc

```
call plug#begin($VIM.'\vimfiles\plugins')
Plug 'wakatime/vim-wakatime'
call plug#end()
filetype plugin indent on

set laststatus=2
```

and this startuptime log

```


times in msec
 clock   self+sourced   self:  sourced script
 clock   elapsed:              other lines

000.000  000.000: --- VIM STARTING ---
000.000  000.000: Allocated generic buffers
002.000  002.000: locale set
004.000  002.000: GUI prepared
004.000  000.000: clipboard setup
004.000  000.000: window checked
004.000  000.000: inits 1
010.000  006.000: parsing arguments
010.000  000.000: expanding arguments
011.000  001.000: shell init
011.000  000.000: inits 2
013.000  002.000: init highlight
018.000  001.000  001.000: sourcing C:\app\vim\vimfiles\autoload\plug.vim
036.000  001.000  001.000: sourcing C:\app\vim\vim80\lang\menu_ja_jp.utf-8.vim
038.000  000.000  000.000: sourcing C:\app\vim\vim80\autoload\paste.vim
099.000  065.000  064.000: sourcing C:\app\vim\vim80/menu.vim
099.000  078.000  013.000: sourcing C:\app\vim\vim80\filetype.vim
100.000  000.000  000.000: sourcing C:\app\vim\vim80\ftplugin.vim
102.000  000.000  000.000: sourcing C:\app\vim\vim80\indent.vim
105.000  000.000  000.000: sourcing C:\app\vim\vim80\syntax\syncolor.vim
106.000  002.000  002.000: sourcing C:\app\vim\vim80\syntax\synload.vim
106.000  003.000  001.000: sourcing C:\app\vim\vim80\syntax\syntax.vim
108.000  000.000  000.000: sourcing C:\app\vim\vim80\filetype.vim
109.000  000.000  000.000: sourcing C:\app\vim\vim80\ftplugin.vim
110.000  000.000  000.000: sourcing C:\app\vim\vim80\indent.vim
111.000  095.000  013.000: sourcing test_vimrc
111.000  003.000: sourcing vimrc file(s)
6801.000  001.000  001.000: sourcing C:\app\vim\vimfiles\plugins\vim-wakatime\plugin\wakatime.vim
6807.000  001.000  001.000: sourcing C:\app\vim\vim80\plugin\getscriptPlugin.vim
6807.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\gzip.vim
6808.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\logiPat.vim
6809.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\manpager.vim
6810.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\matchparen.vim
6811.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\netrwPlugin.vim
6812.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\rrhelper.vim
6813.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\spellfile.vim
6814.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\tarPlugin.vim
6815.000  001.000  001.000: sourcing C:\app\vim\vim80\plugin\tohtml.vim
6815.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\vimballPlugin.vim
6816.000  000.000  000.000: sourcing C:\app\vim\vim80\plugin\zipPlugin.vim
6816.000  6702.000: loading plugins
6817.000  001.000: loading packages
6817.000  000.000: loading after plugins
6817.000  000.000: inits 3
6818.000  001.000  001.000: sourcing $VIMRUNTIME\menu.vim
6822.000  003.000  003.000: sourcing $HOME\_gvimrc
8781.000  001.000  001.000: sourcing C:\app\vim\vim80\syntax\syncolor.vim
8781.000  1959.000: starting GUI
8782.000  001.000: reading viminfo
8816.000  034.000: GUI delay
8816.000  000.000: setting raw mode
8816.000  000.000: start termcap
8816.000  000.000: clearing screen
8817.000  001.000: opening buffers
8819.000  002.000: BufEnter autocommands
8819.000  000.000: editing files in windows
8821.000  002.000: VimEnter autocommands
8821.000  000.000: before starting main loop
8835.000  014.000: first screen update
8835.000  000.000: --- VIM STARTED ---

```

and and vim version

```
VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Nov  7 2017 10:57:15)
MS-Windows 64-bit console version
Included patches: 1-1274
Compiled by rmaejima@INTRA
Huge version without GUI.  Features included (+) or not (-):
+acl                +extra_search       +mouse              +tag_old_static
+arabic             +farsi              -mouseshape         -tag_any_white
+autocmd            +file_in_path       +multi_byte_ime/dyn -tcl
-balloon_eval       +find_in_path       +multi_lang         +termguicolors
-browse             +float              -mzscheme           +terminal
++builtin_terms     +folding            -netbeans_intg      -tgetent
+byte_offset        -footer             +num64              -termresponse
+channel            +gettext/dyn        +packages           +textobjects
+cindent            +guess_encode       +path_extra         +timers
+clientserver       -hangul_input       +perl/dyn           +title
+clipboard          +iconv/dyn          +persistent_undo    -toolbar
+cmdline_compl      +insert_expand      -postscript         +user_commands
+cmdline_hist       +job                +printer            +vertsplit
+cmdline_info       +jumplist           +profile            +virtualedit
+comments           +kaoriya            +python/dyn         +visual
+conceal            +keymap             +python3/dyn        +visualextra
+cryptv             +lambda             +quickfix           +viminfo
+cscope             +langmap            +reltime            +vreplace
+cursorbind         +libcall            +rightleft          +wildignore
+cursorshape        +linebreak          -ruby               +wildmenu
+dialog_con         +lispindent         +scrollbind         +windows
+diff               +listcmds           +signs              +writebackup
+digraphs           +localmap           +smartindent        -xfontset
-dnd                +lua/dyn            +startuptime        -xim
-ebcdic             +menu               +statusline         -xpm_w32
+emacs_tags         -migemo             -sun_workshop       -xterm_save
+eval               +mksession          +syntax             
+ex_extra           +modify_fname       +tag_binary         
   system vimrc file: "$VIM\vimrc"
     user vimrc file: "$HOME\_vimrc"
 2nd user vimrc file: "$HOME\vimfiles\vimrc"
 3rd user vimrc file: "$VIM\_vimrc"
      user exrc file: "$HOME\_exrc"
  2nd user exrc file: "$VIM\_exrc"
       defaults file: "$VIMRUNTIME\defaults.vim"
Compilation: cl -c /W3 /nologo  -I. -Iproto -DHAVE_PATHDEF -DWIN32  -DFEAT_CSCOPE -DFEAT_TERMINAL  -DFEAT_JOB_CHANNEL      -DWINVER=0x0501 -D_WIN32_WINNT=0x0501 /MP -DHAVE_STDINT_H /Ox /GL -DNDEBUG  /MD -DFEAT_MBYTE_IME -DDYNAMIC_IME -DFEAT_MBYTE -DDYNAMIC_ICONV -DDYNAMIC_GETTEXT -DFEAT_LUA -DDYNAMIC_LUA  -DDYNAMIC_LUA_DLL=\"lua5.3.dll\" -DFEAT_PYTHON -DDYNAMIC_PYTHON -DDYNAMIC_PYTHON_DLL=\"python27.dll\" -DFEAT_PYTHON3 -DDYNAMIC_PYTHON3 -DDYNAMIC_PYTHON3_DLL=\"python35.dll\" -DFEAT_PERL -DPERL_IMPLICIT_CONTEXT -DPERL_IMPLICIT_SYS -DDYNAMIC_PERL -DDYNAMIC_PERL_DLL=\"perl524.dll\" -DFEAT_HUGE /Fd.\ObjCULYHAMD64/ /Zi
Linking: link  /nologo /subsystem:console /LTCG:STATUS oldnames.lib kernel32.lib advapi32.lib shell32.lib gdi32.lib  comdlg32.lib ole32.lib uuid.lib /machine:AMD64  /nodefaultlib msvcrt.lib  user32.lib  /nodefaultlib:lua5.3.lib   /nodefaultlib:python27.lib /nodefaultlib:python35.lib    WSock32.lib  /PDB:vim.pdb -debug

```

Do you have any solutions?

Best Regards,
