### ISSUE TITLE
Crashes if a file starts with a `!`

### ISSUE THREAD

**Issue by thejspr** [wakatime/vim-wakatime#29]
Getting an error in `cli.py` when opening a file that starts with a bang, e.g. `!inbox.md`.

![image](https://cloud.githubusercontent.com/assets/293672/8079027/4f067816-0f62-11e5-9cd2-44cd07288943.png)

**Comment by alanhamlett** [comment]
Fixed with 3162cbdaacf105ca28096f20a13278cdab6f551d
