### ISSUE TITLE
No option to enter API key

### ISSUE THREAD

**Issue by fayimora** [wakatime/vim-wakatime#30]
Hey folks,

I installed wakatime via Vundle. I restarted vim and did not get any prompt asking for an API key. Any idea what i'm doing wrong?

**Comment by fayimora** [comment]
Just checked the dashboard and it seems to be working..weird

**Comment by alanhamlett** [comment]
All Waka plugins share the same config file, so you probably had another extension already installed.

**Comment by fayimora** [comment]
Yeah I figured. Thanks

**Comment by joshuayanggithub** [comment]
7 years late, but same thing happened to me and was resolved. 

> All Waka plugins share the same config file, so you probably had another extension already installed.

I've used Wakatime with Vscode already, so I guess this is what happened. Interested in the exact file path on UNIX systems.
