### ISSUE TITLE
UI errors

### ISSUE THREAD

**Issue by fayimora** [wakatime/vim-wakatime#31]
Once in a while my Vim UI gets scrambled with this:

![screenshot 2015-07-03 20 59 33](https://cloud.githubusercontent.com/assets/648684/8504293/c3a8c04a-21c6-11e5-943b-b31c10531baf.png)

Any ideas on how to fix this?

**Comment by alanhamlett** [comment]
Update the plugin with `:BundleUpdate` inside Vim and the error will be fixed.

**Comment by fayimora** [comment]
ok thanks :+1:

**Comment by lvwrence** [comment]
I'm getting something similar here.

**Comment by alanhamlett** [comment]
@lvwrence is it the same error message? If not, can you create a new issue with your error message here please:

https://github.com/wakatime/vim-wakatime/issues/new

**Comment by lvwrence** [comment]
@alanhamlett Actually, I reinstalled wakatime manually and it seems to work now. Thanks!
