### ISSUE TITLE
Strange graphical glitch when enabling wakatime

### ISSUE THREAD

**Issue by SeeThruHead** [wakatime/vim-wakatime#32]
![glitch](https://www.dropbox.com/s/hj00leqq0lzsplm/Screenshot%202015-07-21%2011.06.03.png?dl=0&raw=1)

The line on the bottom is repeated on every pane switch.
So this happens when enabling the vim-wakatime plugin. Stops once disabled.

**Comment by alanhamlett** [comment]
Can you list all other plugins you have installed, and I'll test with those? I think it's probably not playing nice with another plugin.

**Comment by alanhamlett** [comment]
I was able to reproduce this using your vimrc. Running this command cleans it up `:redraw!`. Looks like a bug in airline?

**Comment by SeeThruHead** [comment]
I though that too but removing the airline plugin didn't fix the issue. When I get a free second I will start disabling plugins one by one and report back.

**Comment by alanhamlett** [comment]
Ok, curious to see what u find!

**Comment by kaldown** [comment]
I have the same issue on clean vimrc (or at least with only vundle installed).
It's easy to reproduce, just :w in vim, and you'll see addition line at the bottom.
