### ISSUE TITLE
'NoneType' has no attribute 'name'

### ISSUE THREAD

**Issue by dan-silva** [wakatime/vim-wakatime#33]
I'm getting this error on `stats.py`, at line 43. 
I'm sorry for just citing this issue instead of providing a patch, but I'm out of time right now :/

**Comment by alanhamlett** [comment]
Thank you!

**Comment by dan-silva** [comment]
it was fast haha thank you! :D

**Comment by alanhamlett** [comment]
Was a simple one-line bug :smile:
