### ISSUE TITLE
v4.0.4 can't work normally on my svn project

### ISSUE THREAD

**Issue by l7l1l0l** [wakatime/vim-wakatime#34]
python -V : 2.7.9
There are many exceptions on ~/.wakatime.log when I edit svn files.
The error info is "../vim-wakatime/plugin/packages/wakatime/projects/subversion.py", line 73, in _get_info line = bytes.decode(line) UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 0: ordinal not in range(128)". 
When I modify subversion.py and add  "
import sys
reload(sys)
sys.setdefaultencoding('utf-8')", there is anthor error info:"/home/RogerLuo/.vim/bundle/vim-wakatime/plugin/packages/wakatime/projects/subversion.py", line 38, in name return u(self.info['Repository Root'].split('/')[-1]) KeyError: 'Repository Root'"

What can I do if I want use wakatime?

My Linux setting is:
~/.vimrc
...
set enc=utf-8
set fencs=utf-8,ucs-bom,shift-jis,gb18030,gbk,gb2312,cp936
set langmenu=zh_CN.UTF-8
set helplang=cn
...

~/.bash_profile
...
export LC_ALL='zh_CN.utf8'
...

**Comment by alanhamlett** [comment]
Can you try with v4.0.5 of this plugin?

**Comment by l7l1l0l** [comment]
Good! Thank you very much!
