### ISSUE TITLE
Neoterm on Neovim

### ISSUE THREAD

**Issue by gacha** [wakatime/vim-wakatime#37]
When switching to a neoterm split, error is raised:
```
Error detected while processing function <SNR>63_handleActivity..<SNR>63_Api:
line   22:
E499: Empty file name for '%' or '#', only works with ":p:h": silent !'python' '-W' 'ignore' '/Users/me/.config/nvim/bundle/vim-wakatime/
plugin/packages/wakatime/cli.py' '--file' 'term://.//27524:/bin/zsh;#neoterm-3' '--plugin' 'vim/704 vim-wakatime/4.0.6' &
```

When switching to normal neovim terminal there is no error.

**Comment by alanhamlett** [comment]
f497ef6ff49c21f767f7c9ccf8e78c548aac7bec might have fixed it, by checking if the file is `empty()`. Can you comfirm?

**Comment by alanhamlett** [comment]
Also, how do I use neoterm split? I only know how to open a normal `:terminal` with nvim.

**Comment by alanhamlett** [comment]
6cf829f08d72ffe56a794a2e4ada5689e7d68237 should fix it by checking if the file starts with `term:`

**Comment by gacha** [comment]
Thank you Alan, it's working. To open terminal in a split type `:below sp term://$SHELL`

**Comment by alanhamlett** [comment]
Awesome! :+1:

**Comment by acgtyrant** [comment]
So does vim-wakatime support Neovim? Thank you!

**Comment by alanhamlett** [comment]
@acgtyrant yes, vim-wakatime works with Neovim.
