### ISSUE TITLE
vim reports syntax = python but dashboard reports Other

### ISSUE THREAD

**Issue by bulletmark** [wakatime/vim-wakatime#38]
I've just started trying wakatime but the first thing I notice is that my dashboard reports "Other" when editing my python file. Vim reports syntax=python. It seems to be basing the language just from the file (.py) extension? The python utility I am editing does not have a filename ending in .py. The plugin should use the vim determined syntax.

**Comment by alanhamlett** [comment]
Add this as the second line of your python file and wakatime will detect the language as Python:
`# vim: set filetype=python`

**Comment by bulletmark** [comment]
Hopefully that is not a proposed solution?

The filetype already was set to python anyhow by vim. In fact, that is a prerequisite for vim to set the syntax to python which I already stated is the case.

I had a quick look at this extension's code and it currently tries to guess the language itself using filename, extension, scanning directly for a modeline (yuk!), etc. If syntax is set then Vim has already done the hard work determining the language so this extension should firstly just check the syntax setting and return that if set. In fact I would argue that any vim programmers around who don't care to ensure their syntax setting is being set properly also would not care less about what language wakatime is reporting.

**Comment by alanhamlett** [comment]
It's a temporary solution when there's not enough code in the file for Pygments to detect the language. Having a `.py` extension helps Pygments when there aren't enough tokens in the file to detect the language.

The more permanent solution is to add a new command line argument to [wakatime-cli](https://github.com/wakatime/wakatime) that accepts an alternate language when one can not be detected. Vim's languages don't map directly to Pygments, so we can't send them as-is to the api. We would have to build a map of Vim's languages to Pygments' languages. For example, `python` from Vim should be changed to `Python` for WakaTime.

**Comment by bulletmark** [comment]
Yes, I realized that you would have to map the vim syntax value to whatever you need but surely that is pretty simple and ultimately a much better approach? You can then remove all those big but otherwise superfluous packages you are bundling just to determine this (and which are not doing it very well anyhow). I checked the download size of your vundle extension dir and it is massive compared to all my other many extensions.

**Comment by alanhamlett** [comment]
We won't remove Pygments, because it detects languages quite well. Most editors don't support detecting languages, and if they do they wouldn't use the same language names as Vim so Pygments also helps standardize things.

**Comment by bulletmark** [comment]
Understood, but we are talking about this vim extension here. Just map the vim determined syntax to the Pygments name. Vim clearly does it better and surely that is much more efficient than bundling all that heavy stuff?

**Comment by alanhamlett** [comment]
Implemented with 8f4f7b04f3602cfefbbea0db830c944d8768ee2b.
