### ISSUE TITLE
vim creshed with retry error

### ISSUE THREAD

**Issue by shinux** [wakatime/vim-wakatime#39]
Error: 'Retry' object has no attribute 'raise_on_status'

Is this error caused by API key ?

**Comment by alanhamlett** [comment]
Can you reproduce the error from Terminal or somehow get a full Traceback with line numbers?

Try running this command from Terminal:
`python ~/.vim/bundle/vim-wakatime/plugin/packages/wakatime/cli.py --file THE_FILE_YOU_WERE_EDITING_IN_VIM`

**Comment by shinux** [comment]
having tried your command, but terminal returns me nothing.

 this seems to be an urllib3 error

**Comment by alanhamlett** [comment]
Yes it is a bug in urllib3 but before we can submit an issue to them we should debug a little. Can you paste the output of this Terminal command:

```
pip freeze | grep -e "requests\|urllib3"
```

**Comment by shinux** [comment]
Got no requests nor urllib3 in my global environment, and I can't reproduce right now...

I'll focus on testing `urlopen` function from urllib3.

Thanks for your patient support 💯

**Comment by alanhamlett** [comment]
Ok that's good, then it must be a bug in the latest version of urllib3. I'll try to reproduce it too since it looks like that method is only used in one place and shouldn't be too complicated.

**Comment by bausmeier** [comment]
@alanhamlett I'm getting the same issue. Full traceback here: https://gist.github.com/bausmeier/00720abdfdc98bb2e2a1b48fc00d39b5.

**Comment by alanhamlett** [comment]
Thanks @bausmeier, just created an issue for this at shazow/urllib3#871

**Comment by alanhamlett** [comment]
Using master version of urllib3 because it looks like a new version of requests won't be released for a while.
