### ISSUE TITLE
Visual glitch when I run `:help`

### ISSUE THREAD

**Issue by rafaelrinaldi** [wakatime/vim-wakatime#40]
Every time I run `:help` I get this weird glitch.

![screen shot 2016-06-14 at 3 05 16 pm](https://cloud.githubusercontent.com/assets/87162/16055996/82d042b4-3241-11e6-8585-46f025f38b19.png)

It seems to be related to a Python feature that is expected. Does anyone know how to workaround this?

**Comment by alanhamlett** [comment]
Somehow the `pygments.util.ClassNotFound` exception is not being caught correctly. This fixes it by catching all exceptions, until we can provide a more specific fix.

**Comment by alanhamlett** [comment]
Should be fixed now with wakatime/wakatime@4ce1419cc8e6153b2501891fb284895b9931558e. Can you upgrade vim-wakatime and see if it still happens?

**Comment by rafaelrinaldi** [comment]
@alanhamlett Thanks for looking into this. I can confirm that I no longer see the issue 👍
