### ISSUE TITLE
Huge CPU hit when doing :bufdo

### ISSUE THREAD

**Issue by joaumg** [wakatime/vim-wakatime#45]
Hello, I have a somewhat huge'ish amount of files ( ~140 files ), and when I run a bufdo in all of them, wakatime ( exactly python -W ignore /home/.../vim-wakatime/plugin/packages/wakatime/cli.py --entity ... ) spawns like 10+ processes, each consuming up to 5% of the cpu ( 50% in total ).

Is there a way to disable wakatime on bufdo's ? Is this expected behavior?

![cpu_usage](https://cloud.githubusercontent.com/assets/7634886/22784723/5965511a-eeb8-11e6-830b-6021ca59c5a8.png)

**Comment by alanhamlett** [comment]
What's the rest of that python command that's cut off on the right?

**Comment by alanhamlett** [comment]
If your bufdo command is writing to all open buffers, then WakaTime will think your coding in all those buffers. Maybe there's a way to detect bufdo usage and disable WakaTime for that command?

The way other editor plugins mitigate this is by buffering heartbeats in memory, then attaching them to one Python process as `--extra-heartbeats` every 10 seconds. That way all these Python processes would become one:
https://github.com/wakatime/sublime-wakatime/blob/dcc782338d31b7d7326cb6b73f66daeb8c73bb29/WakaTime.py#L529

**Comment by alanhamlett** [comment]
Fixed with 8a72498e138b5c82c667674f03cd704d6193d423. Can you upgrade the plugin and see if the performance is better when using `:bufdo`?
