### ISSUE TITLE
Wakatime keeps asking for api_key even .wakatime.cfg is set

### ISSUE THREAD

**Issue by vincentzhezhang** [wakatime/vim-wakatime#46]
I have my wakatime set and running a while ago without problem, but recently I encountered this issue, not sure if it is caused by recent updates. The output on startup is:

![wakatime](https://cloud.githubusercontent.com/assets/1330120/25119704/d8151408-244d-11e7-849c-16a579d312a1.png)

My setup (working properly for a long time until last few weeks):
```
NeoVim v0.2.0-891-g091a99a
Ubuntu 14.04 lts
has python virtualenv and set the g:wakatime_PythonBinary value
self-signed SSL certificate
```

any help is much appreciated.

**Comment by alanhamlett** [comment]
Try updating the plugin and let me know if it's fixed.

**Comment by vincentzhezhang** [comment]
It still asks me the api key on start up, however, error messages are gone.
After a few tries, it left duplicate entries in my .wakatime.cfg like this:
![wakatime cfg](https://cloud.githubusercontent.com/assets/1330120/25217398/4c875242-25d9-11e7-9d4e-233fe3cc6b5e.png)

**Comment by alanhamlett** [comment]
`[settings]` should be the first line of that file, not the second. Try moving `[settings]` up one line, or just delete the file and enter your api key when Vim prompts again.

**Comment by vincentzhezhang** [comment]
Yup, that solved the problem, thanks!
It's a bit weird though, previously there is only one line in the config. So I assume the `[settings]` section header is added recently?

**Comment by alanhamlett** [comment]
`[settings]` was added in 2013 when we started using the INI format ([changelog](https://github.com/wakatime/vim-wakatime/blob/master/HISTORY.rst#140-2013-12-13)).
