### ISSUE TITLE
Huge delay added to switching tabs

### ISSUE THREAD

**Issue by Chilinot** [wakatime/vim-wakatime#47]
I'm using lots of tabs with many windows when I'm coding and when I added this plugin to my Vim the performance really tanked. From taking a couple milliseconds between tab switches it now takes around 0.5+ everytime I switch tab in Vim.

My guess is that this line is the cause:
`autocmd BufEnter * call s:handleActivity(s:false)` found here: https://github.com/wakatime/vim-wakatime/blob/master/plugin/wakatime.vim#L312

Does it really have to call this method every single time on every single buffer in the tab I switch to?
Could this be refactored to use the new async API that has been implemented in the latest Vim or NeoVim?

**Comment by alanhamlett** [comment]
Just to make sure, debug mode is turned off in your `~/.wakatime.cfg` file?

When `debug = true` the plugin does some networking in the foreground process instead of the background when switching to a new buffer.

> Could this be refactored to use the new async API that has been implemented in the latest Vim or NeoVim?

Yes, that would improve performance.

**Comment by Chilinot** [comment]
Yea it is disabled.

**Comment by alanhamlett** [comment]
Ok, I'll update the plugin to use the new async api if available.

**Comment by alanhamlett** [comment]
Instead of using async, I've buffered the heartbeats in memory. Can you update the plugin and see if performance improves when switching tabs? If it's improved enough, we can postpone using the async `job_start` for now.

**Comment by Chilinot** [comment]
Vim seems a lot snappier now compared to before. Huge thanks :)

**Comment by alanhamlett** [comment]
👍 

Awesome! Glad it's fixed!

**Comment by Chilinot** [comment]
It would seem that Vim no longer reports any time to wakatime. I have zero time registered from the day this issue was solved up to now.

**Comment by alanhamlett** [comment]
How about with the latest version?

**Comment by Chilinot** [comment]
Yes, latest version solves the issue. I was looking through the log and it is filled with these errors (that are no longer happening). In case you would find it useful anyway:
`"now": "2017/04/25 16:04:34 +0000", "version": "8.0.0", "plugin": "vim/704 vim-wakatime/4.0.15", "time": 25696.623507, "level": "ERROR", "message": "{'response_code': 400, 'response_content': u'{\\n  \"errors\": {\\n    \"time\": [\\n  
    \"Number must be between 1388534400 and 99999999999.\"\\n    ]\\n  }\\n}\\n'}"}`

**Comment by alanhamlett** [comment]
That was the same issue as #48. I can write a script to parse your `~/.wakatime.log` file and replay that coding activity if that's useful?

**Comment by Chilinot** [comment]
Oh my bad. No that wont be needed but thanks anyway :)

**Comment by alanhamlett** [comment]
An update, now vim-wakatime uses Vim's async `job_start` for improved performance with 99ffbf39cf57c9c10204e02f8991e113f43bbf88.

It also buffers heartbeats to prevent spawning too many python processes.
