### ISSUE TITLE
Errors when using zsh as vim shell

### ISSUE THREAD

**Issue by Ferdev** [wakatime/vim-wakatime#55]
If you set `set shell=zsh\ --login` in your vim config, the plugin stops working.

I can see this error in the `messages` panel:

```
[WakaTime] Heartbeat Command: 'python' '-W' 'ignore' '/Users/fer/Dropbox/dotfiles/.vim/plugged/vim-wakatime/plugin/packages/wakatime/cli.py' '--entity' '/path/to/my/file.elm' '--time' '150836
3996.038438' '--plugin' 'vim/800 vim-wakatime/6.0.1' '--write' '--language' 'elm'^@[WakaTime] Error: executing job failed: No such file or directory
```

This error happens in both macOS and Arch Linux.

**Comment by alanhamlett** [comment]
Which version of Vim are you using? Can you try updating vim-wakatime and see if it's fixed now?

**Comment by Ferdev** [comment]
I'm using `VIM - Vi IMproved 8.0 (2016 Sep 12, compiled Oct  7 2017 13:50:55)`

It does work now, thanks! You've got yourself a new client, sir.
