### ISSUE TITLE
100% CPU usage by Python background process

### ISSUE THREAD

**Issue by alanhamlett** [wakatime/vim-wakatime#57]
From Twitter:

https://twitter.com/FomoTrader/status/925501979123765248

**Comment by alanhamlett** [comment]
Which OS, Vim version, vim-wakatime version, and Python version do you have? Are there multiple python processes or just one process taking up 100% CPU?

**Comment by jalcine** [comment]
That tweet doesn't exist anymore.

**Comment by alanhamlett** [comment]
Maybe he resolved it.. I'll close this issue unless you're also having Python take 100% cpu?

**Comment by jalcine** [comment]
Nope; just here to help close out tasks!

**Comment by alanhamlett** [comment]
Thanks, much appreciated!
