### ISSUE TITLE
Adds about 14 seconds of load time to neovim

### ISSUE THREAD

**Issue by partounian** [wakatime/vim-wakatime#58]
Using https://github.com/bchretien/vim-profiler to profile neovim startup time and running about 10 tests I can see it averages adding about 14 seconds of load time. 

macOS 10.13.1 (newest stable High Sierra)
nVim 0.2.1
python2 and python3 neovim 0.2.0
wakatime 7.0.1

**Comment by alanhamlett** [comment]
Does it still happen after upgrading vim-wakatime?

**Comment by partounian** [comment]
Yes, at least according to the script.

**Comment by partounian** [comment]
Sorry I assumed the time was in seconds, but I guess it's milliseconds. My mistake.

**Comment by alanhamlett** [comment]
Oh, got it. I'll close this issue then 👍
