### ISSUE TITLE
Time is not tracked if started by an other application

### ISSUE THREAD

**Issue by CptPie** [wakatime/vim-wakatime#59]
I have noticed that wakatime doesn't track the time if vim is started by an other application (in my case ghci).

Steps to reproduce: 
-Start ghci from terminal
-set vim as default editor (:set editor vim)
-start vim with the command :e 

It could be possible that i set up the wakatime vim integration wrong but as it tracked other files edited with vim i don't think so.

**Comment by alanhamlett** [comment]
If ghci changes your PATH env variable, that could cause WakaTime to not find Python. Can you turn on debug mode (`:WakaTimeDebugEnable`) then tail your `~/.wakatime.log` file? If python is detected, you will see log lines generated, otherwise you will not see anything new in the logfile when typing in a file in Vim.

**Comment by CptPie** [comment]
It seems the log lines are generated:
`{"now": "2017/11/17 20:04:35 +0100", "version": "9.0.0", "plugin": "vim/800 vim-wakatime/6.0.3", "time": 1510945460.621058, "caller": "/home/fabian/.vim/bundle/vim-wakatime/plugin/packages/wakatime/dependencies/__init__.py", "lineno": 122, "file": "/home/fabian/Desktop/Uni-Unterlagen/AI FS 3/ifp/13.11.2017.hs", "level": "DEBUG", "message": "Parsing dependencies not supported for haskell.HaskellParser"}
{"now": "2017/11/17 20:04:35 +0100", "version": "9.0.0", "plugin": "vim/800 vim-wakatime/6.0.3", "time": 1510945460.621058, "caller": "/home/fabian/.vim/bundle/vim-wakatime/plugin/packages/wakatime/main.py", "lineno": 77, "file": "/home/fabian/Desktop/Uni-Unterlagen/AI FS 3/ifp/13.11.2017.hs", "level": "DEBUG", "message": "Sending heartbeat to api at https://api.wakatime.com/api/v1/heartbeats"}
{"now": "2017/11/17 20:04:35 +0100", "version": "9.0.0", "plugin": "vim/800 vim-wakatime/6.0.3", "time": 1510945460.621058, "caller": "/home/fabian/.vim/bundle/vim-wakatime/plugin/packages/wakatime/main.py", "lineno": 121, "file": "/home/fabian/Desktop/Uni-Unterlagen/AI FS 3/ifp/13.11.2017.hs", "level": "DEBUG", "message": "{'time': 1510945460.621058, 'entity': '/home/fabian/Desktop/Uni-Unterlagen/AI FS 3/ifp/13.11.2017.hs', 'type': 'file', 'lines': 147, 'language': 'Haskell'}"}
{"now": "2017/11/17 20:04:37 +0100", "version": "9.0.0", "plugin": "vim/800 vim-wakatime/6.0.3", "time": 1510945460.621058, "caller": "/home/fabian/.vim/bundle/vim-wakatime/plugin/packages/wakatime/main.py", "lineno": 237, "file": "/home/fabian/Desktop/Uni-Unterlagen/AI FS 3/ifp/13.11.2017.hs", "level": "DEBUG", "message": "{'response_code': 201}"}`

but i noticed in the log file there were entries that seemed like some errors:

`{"now": "2017/11/14 10:31:29 +0100", "version": "8.0.3", "plugin": "sublime/2221 sublime-wakatime/7.0.23", "time": 1510651766.434874, "level": "WARNING", "message": "{'TypeError': \"unsupported operand type(s) for -=: 'Retry' and 'int'\", 'traceback': 'Traceback (most recent call last):\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connection.py\", line 141, in _new_conn\\n    (self.host, self.port), self.timeout, **extra_kw)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/util/connection.py\", line 83, in create_connection\\n    raise err\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/util/connection.py\", line 73, in create_connection\\n    sock.connect(sa)\\nsocket.timeout: timed out\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connectionpool.py\", line 600, in urlopen\\n    chunked=chunked)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connectionpool.py\", line 345, in _make_request\\n    self._validate_conn(conn)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connectionpool.py\", line 844, in _validate_conn\\n    conn.connect()\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connection.py\", line 284, in connect\\n    conn = self._new_conn()\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connection.py\", line 146, in _new_conn\\n    (self.host, self.timeout))\\nwakatime.packages.requests.packages.urllib3.exceptions.ConnectTimeoutError: (<wakatime.packages.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f36f3608898>, \\'Connection to api.wakatime.com timed out. (connect timeout=60)\\')\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/main.py\", line 158, in send_heartbeat\\n    verify=not nosslverify)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/sessions.py\", line 535, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/sessions.py\", line 488, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/sessions.py\", line 609, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/adapters.py\", line 423, in send\\n    timeout=timeout\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/connectionpool.py\", line 649, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/home/fabian/.config/sublime-text-2/Packages/WakaTime/packages/wakatime/packages/requests/packages/urllib3/util/retry.py\", line 328, in increment\\n    total -= 1\\nTypeError: unsupported operand type(s) for -=: \\'Retry\\' and \\'int\\'\\n'}"}`

**Comment by CptPie** [comment]
Seems like its working now even though i didn't change anything

**Comment by alanhamlett** [comment]
This was probably related to wakatime/wakatime#111
