### ISSUE TITLE
AsyncNeovimHandler errors out when debug is on

### ISSUE THREAD

**Issue by mixxorz** [wakatime/vim-wakatime#62]
Error log:

```
Error detected while processing function <SNR>55_AsyncNeovimHandler:

E691: Can only compare List with List

Error detected while processing function <SNR>55_AsyncNeovimHandler:

E15: Invalid expression: s:is_debug_on && a:output != ''

[WakaTime] Error: 127
```

I turned on debug mode because the plugin wasn't tracking my time.

vim-wakatime 7.0.4
nvim 0.2.2
macOS High Sierra

**Comment by alanhamlett** [comment]
What's the output of this command in your NeoVim:

`:echo printf('patch-7.4-2344=%d, job_start=%d, jobstart=%d', has('patch-7.4-2344'), exists('*job_start'), exists('*jobstart'))`

**Comment by mixxorz** [comment]
Thanks for the quick reply!

Here's the output.

```
patch-7.4-2344=1, job_start=0, jobstart=1
```

**Comment by alanhamlett** [comment]
Can you update the plugin and see if it's fixed?

**Comment by mixxorz** [comment]
Yep! That fixed it! That was so fast. Thanks!
