### ISSUE TITLE
Neovim Intermittent error 102

### ISSUE THREAD

**Issue by mixxorz** [wakatime/vim-wakatime#63]
Thanks for your help with #62, but now I'm encountering a different error. WakaTime works for the most part, but I get these annoying WakaTime: Error 102 messages from time to time (my suspicion is when the internet is intermittent). The exception comes from `NeovimAsyncExitHandler`.

I will update this issue with the exact error log if I encounter it again, but I'm just opening this issue now just in case it's a trivial bug.

Platform: macOS High Sierra
Vim version: Neovim v0.2.2
vim-wakatime version: v7.0.5

**Comment by alanhamlett** [comment]
This error is usually hidden, unless debug mode is turned on. Can you check if debug mode is on in your `~/.wakatime.cfg` file?

Also, to turn off debug mode inside Vim, run this command:
`:WakaTimeDebugDisable`

**Comment by mixxorz** [comment]
Ah. Right. My bad. Thanks!
