### ISSUE TITLE
Last version doesn't track time anymore ?

### ISSUE THREAD

**Issue by ffesseler** [wakatime/vim-wakatime#65]
Hello,

I've noticed my activity has not been recorded for some time (2-3 weeks).

I don't know exactly what's going on and if it's related to the recent plugin updates or not.

Any tip to find the issue ?

**Comment by alanhamlett** [comment]
Can you first try re-installing the plugin to make sure you're on the latest version?

**Comment by ffesseler** [comment]
Re-installing the plugin fixed the issue, thank you !
