### ISSUE TITLE
Cannot log time. Exception

### ISSUE THREAD

**Issue by tiev** [wakatime/vim-wakatime#66]
Nothing much to say. It has exceptions, and cannot log time.

![screen shot 2018-04-02 at 2 16 41 pm](https://user-images.githubusercontent.com/3033842/38187149-9c0fb76a-3680-11e8-892b-42553f8134be.png)

**Comment by alanhamlett** [comment]
Looks like a duplicate of #64. Try deleting `/Users/viett/.vim/plugged/vim-wakatime` then re-installing the plugin.

**Comment by tiev** [comment]
It works. Thanks
