### ISSUE TITLE
WakaTime doesn't work on Windows

### ISSUE THREAD

**Issue by iamkarlson** [wakatime/vim-wakatime#72]
Hi all,
I'm trying to get wakatime plugin working with my neovim instance but with no success. Here's my wakatime.cfg:

```
[settings]
api_key= ____my_key____
my_key
proxy = 
debug=true
disable_threading=false
vi_redraw=auto
```

First, I got error that python is not recognizeble command. Then I set: 
```
let g:wakatime_PythonBinary = 'C:\Python37\python.exe'  " (Default: 'python')
```

And error becomes such that:
![image](https://user-images.githubusercontent.com/4534374/48704051-df429e00-ebf5-11e8-8c22-6d2216d238f5.png)

```
[WakaTime] Error 1: The filename, directory name, or volume label syntax is incorrect.^M
```

.wakatime.log is empty. I've tried to delete the whole folder from .vim/bundles and reinstall - the same issue.

**Comment by alanhamlett** [comment]
What if you change it to:

`let g:wakatime_PythonBinary = 'C:\Python37\python'  " (Default: 'python')`

**Comment by iamkarlson** [comment]
yes, now it works.....

**Comment by kdurant** [comment]
Can someone help me?
My wakatime.cfg:
```
[settings]
debug = false
hidefilenames = false
ignore =
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$
api_key=xxxxxxxxxxxxxxxxxxxxxxx
```
```viml
let g:wakatime_PythonBinary = 'C:\Users\wangj\AppData\Local\Programs\Python\Python36\python'
```
No error message and wakatime.log no data
