### ISSUE TITLE
Can someone help me?

### ISSUE THREAD

**Issue by iamkarlson** [wakatime/vim-wakatime#74]
My wakatime.cfg:
```
[settings]
debug = false
hidefilenames = false
ignore =
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$
api_key=xxxxxxxxxxxxxxxxxxxxxxx
```
```viml
let g:wakatime_PythonBinary = 'C:\Users\wangj\AppData\Local\Programs\Python\Python36\python'
```
No error message and wakatime.log no data

When I run `:WakaTimeDebugEnable`, error message like below
![qq 20181127120741](https://user-images.githubusercontent.com/2704364/49058050-391e1600-f23d-11e8-82e9-f0f17dead8cf.png)

I re-install this plugin, and can't slove problem

_Originally posted by @kdurant in https://github.com/wakatime/vim-wakatime/issues/72#issuecomment-441898082_

**Comment by gandarez** [comment]
Please reopen the issue if it fails again.
