### ISSUE TITLE
recording editing time while im sleeping 

### ISSUE THREAD

**Issue by daywiss** [wakatime/vim-wakatime#76]
The problem im seeing is this:
I work like normal during the day. I go to bed. The next day wakatime shows that I've been editing the same file for 8 hours straight, while I slept.  This puts me near the top10 list of time spent coding. There may be a few things contributing to this, and it may not be possible to really diagnose this issue but I'll just explain what im using. 

I SSH into a headless server using a Mosh client. I use tmux to resume my coding session. I use neovim to edit code. I also have neovim terminals running using split panes in the same window with code. I have several vim plugins, i can list those if it helps.  I dont do anything unusual while i code, when I stop i usually just close/ turn off client computer (not remote server). I do not exit ssh/mosh, end tmux session, close vim, or exit files im working on, i just leave everything as is to resume later.  

Wakatime Version - 7.12, default config, username: daywiss
Nvim - 0.2.2
tmux - 2.1
mosh - 1,.3.2
ubuntu - 16.04.3

**Comment by alanhamlett** [comment]
One of those plugins or tmux must be causing a cursor or keyboard event inside Vim, which makes the wakatime plugin think you're still typing.
