### ISSUE TITLE
Error: 'SSLError': 'HTTPSConnectionPool...

### ISSUE THREAD

**Issue by josedh** [wakatime/vim-wakatime#79]
Hello everyone. Having an issue with vim-wakatime/7.1.3 on vim 8.1.1 on a RHEL6.5 machine (4.5.0-1.el6.elrepo.x86_64)
Its been failing for the last several weeks with this error:
```{'SSLError': 'HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))', 'traceback': 'Traceback (most recent call last):\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 589, in urlopen\\n    conn = self._get_conn(timeout=pool_timeout)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 251, in _get_conn\\n    return conn or self._new_conn()\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 827, in _new_conn\\n    raise SSLError(\"Can\\'t connect to HTTPS URL because the SSL \"\\nurllib3.exceptions.SSLError: Can\\'t connect to HTTPS URL because the SSL module is not available.\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/adapters.py\", line 440, in send\\n    timeout=timeout\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/connectionpool.py\", line 639, in urlopen\\n    _stacktrace=sys.exc_info()[2])\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/urllib3/util/retry.py\", line 388, in increment\\n    raise MaxRetryError(_pool, url, error or ResponseError(cause))\\nurllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/api.py\", line 107, in send_heartbeats\\n    verify=not args.nosslverify)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/sessions.py\", line 555, in post\\n    return self.request(\\'POST\\', url, data=data, json=json, **kwargs)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/sessions.py\", line 508, in request\\n    resp = self.send(prep, **send_kwargs)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/sessions.py\", line 618, in send\\n    r = adapter.send(request, **kwargs)\\n  File \"/home/jdelao/.vim/bundle/vim-wakatime/packages/wakatime/packages/requests/adapters.py\", line 506, in send\\n    raise SSLError(e, request=request)\\nwakatime.packages.requests.exceptions.SSLError: HTTPSConnectionPool(host=\\'api.wakatime.com\\', port=443): Max retries exceeded with url: /api/v1/users/current/heartbeats.bulk (Caused by SSLError(\"Can\\'t connect to HTTPS URL because the SSL module is not available.\"))\\n'}```

I have looked through similiar issues reported in the past and have tried setting:
`165.227.31.73 api.wakatime.com` in my hosts files, to no avail.
Both: `165.227.31.73` and `68.183.248.166` can be pinged from my machine.
I'm starting to think it might be, like the error says, an issue with Python3 (it 'should' be using python2.6)

Any help would be appreciated.

**Comment by gandarez** [comment]
@alanhamlett do you know why SSL module is not available?

**Comment by alanhamlett** [comment]
We've seen this with Anaconda Python and homebrew's Python, which both should always come with the ssl module (wakatime/vscode-wakatime#86 and wakatime/wakatime#104).

Instead of figuring out why Python on the machine is missing ssl, we could:

* run `python -c 'import ssl'` when plugins detect the location of Python
* stop using Python on the machine by bundling wakatime-cli with https://nuitka.net

**Comment by alanhamlett** [comment]
This might also be fixed with [v13.0.4 of wakatime](https://github.com/wakatime/wakatime/blob/master/HISTORY.rst#1304-2020-02-05).

**Comment by gandarez** [comment]
@alanhamlett it seems to be fixed since there's no other user reporting the same error again. May we close it?

**Comment by alanhamlett** [comment]
Yes, and will also be fixed once we switch to the new Go wakatime-cli.
