### ISSUE TITLE
How to set project name in vim?

### ISSUE THREAD

**Issue by eduardoarandah** [wakatime/vim-wakatime#80]
Wakatime Dashboard displays time spent on each of the folders I work on vim. 
```
scripts/
projectname/
css/
Unknown Project
```
How to make them belong to a "project" ?

**Comment by alanhamlett** [comment]
You can use git for each project and the repo is used as the project name, or use a `.wakatime-project` file to set a custom project name. More info in these FAQ answers:

https://wakatime.com/faq#create-projects
https://wakatime.com/faq#rename-projects
