### ISSUE TITLE
Extreme Issue

### ISSUE THREAD

**Issue by Matt-Gleich** [wakatime/vim-wakatime#81]
I keep getting this error:

`wakatime: error: Missing api key. Find your api key from wakatime.com/settings/api-key.`

The reason that this is so bad is that it pops up every time I open terminal. Even after restarting 3 times, I keep getting this error. This happened when I was trying to uninstall the vim plugin that I installed with Pathogon after vim kept crashing due to the fact that the extension installed wrong. That error above isn't the only thing that is displayed in my terminal, here is the rest:
```
(base) matthewgleich@matthewsmbp126 Github $ usage: wakatime [-h] [--entity FILE] [--key KEY] [--write] [--plugin PLUGIN]
                [--time time] [--lineno LINENO] [--cursorpos CURSORPOS]
                [--entity-type ENTITY_TYPE] [--category CATEGORY]
                [--proxy PROXY] [--no-ssl-verify]
                [--ssl-certs-file SSL_CERTS_FILE] [--project PROJECT]
                [--alternate-project ALTERNATE_PROJECT] [--language LANGUAGE]
                [--local-file FILE] [--hostname HOSTNAME] [--disable-offline]
                [--hide-file-names] [--hide-project-names] [--exclude EXCLUDE]
                [--exclude-unknown-project] [--include INCLUDE]
                [--include-only-with-project-file] [--extra-heartbeats]
                [--log-file LOG_FILE] [--api-url API_URL] [--timeout TIMEOUT]
                [--sync-offline-activity SYNC_OFFLINE_ACTIVITY] [--today]
                [--config CONFIG] [--verbose] [--version]
wakatime: error: Missing api key. Find your api key from wakatime.com/settings/api-key.
```

** PLEASE HELP ME I NEED TO BE ABLE TO USE MY TERMINAL**

**Comment by alanhamlett** [comment]
Edit your `~/.wakatime.cfg` file and make sure your `api_key` config matches this:
https://wakatime.com/settings/api-key

**Comment by Matt-Gleich** [comment]
That worked, thanks!
