### ISSUE TITLE
Neovim on Windows 10 echos a NeovimAsyncExitHandler error every few minutes

### ISSUE THREAD

**Issue by thekpaul** [wakatime/vim-wakatime#82]
I use Neovim 0.3.8 on Windows 10 1903 and have both Python 2 and Python 3 working on Neovim. I used [vim-plug](https://www.github.com/junegunn/vim-plug) to install the plugin and correctly added my API Key, but for some reason there is a recurring error with `NeovimAsyncExitHandler` and `:WakaTimeToday` echos `Today: 0 secs` no matter how long I've used Neovim. I've tried manually reinstalling the plugin but it doesn't seem to work, and `:WakaTimeDebugEnable` doesn't write anything to the `~/.wakatime.log` file either.

This is my `~/.wakatime.cfg` :
```
[settings]
debug = false
hidefilenames = false
ignore =
    COMMIT_EDITMSG$
    PULLREQ_EDITMSG$
    MERGE_MSG$
    TAG_EDITMSG$
api_key=_____my_key_____
```

I believe this issue is much similar to those of issues #72 and #74, but I've tried the proposed solution in issue #72, which didn't work either.

Health Check shows Python 2 and 3 working very well in their respective directories :
```
## Python 2 provider (optional)
  - INFO: Using: g:python_host_prog = "C:\Python27\python.exe"
  - INFO: Executable: C:\Python27\python.exe
  - INFO: Python version: 2.7.16
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.

## Python 3 provider (optional)
  - INFO: Using: g:python3_host_prog = "C:\Python37\python.exe"
  - INFO: Executable: C:\Python37\python.exe
  - INFO: Python version: 3.7.4
  - INFO: pynvim version: 0.3.2
  - OK: Latest pynvim is installed.
```

**Comment by thekpaul** [comment]
As an afterthought, this didn't happen when I used Linux under the same conditions.

**Comment by alanhamlett** [comment]
My hunch is it's related to how the plugin runs python here:
https://github.com/wakatime/vim-wakatime/blob/7a544c979ed52042c67a4189687ac53c853f109c/plugin/wakatime.vim#L377

**Comment by alanhamlett** [comment]
Just pushed 29d14cca6593a4809a31cfc3565a366d87426daf that might fix this. Can you update vim-wakatime and see if it's working on Windows now?

**Comment by thekpaul** [comment]
Yes, it writes on the `.log` file now, thank you for the quick fix!
