### ISSUE TITLE
improve documentation -- idleness

### ISSUE THREAD

**Issue by zevaverbach** [wakatime/vim-wakatime#83]
I haven't played with this yet, but am reluctant to because it's not clear whether idleness (no keystrokes for X seconds) is tracked. Is it?

**Comment by alanhamlett** [comment]
Idleness isn't tracked, the plugin code doesn't even execute unless a keypress or other Vim autocmd event occurs:
https://github.com/wakatime/vim-wakatime/blob/29d14cca6593a4809a31cfc3565a366d87426daf/plugin/wakatime.vim#L614

More info here:
https://wakatime.com/faq#afk
