### ISSUE TITLE
Latest CLI Version: 13.0.2 Your CLI Version: 12.0.0

### ISSUE THREAD

**Issue by Ashtonian** [wakatime/vim-wakatime#85]
![image](https://user-images.githubusercontent.com/4212452/69366173-61c3ca80-0c5b-11ea-8f94-f0492d7eb355.png)

**Comment by alanhamlett** [comment]
Just updated wakatime cli with 3d4e98616bb92efa0a959a64b0c004eef18fffe7, updating your vim-wakatime plugin will fix this.
