### ISSUE TITLE
wakatime-cli version falling behind

### ISSUE THREAD

**Issue by HsuanTingLu** [wakatime/vim-wakatime#87]
[Plugin Status](https://wakatime.com/plugins/status)  and [vscode-wakatime](https://github.com/wakatime/vscode-wakatime) shows that the latest version is 13.0.7

**Comment by ckipp01** [comment]
I'm not sure if this is due to this or not, but I also noticed today that I'm seemingly no longer able to authenticate and am always getting an Invalid API Key. Even after re-entering my api key I will continually get:

```
Error detected while processing function <SNR>20_NeovimAsyncExitHandler:
line    6:
[WakaTime] Error 104: Invalid API Key
```

**Comment by HsuanTingLu** [comment]
I'm getting "401 unauthorized" in logs too
it all started from today

(but I'm getting errors from both vim and vscode, using wakatime-cli v13.0.5 and v13.0.7(latest) respectively)

**Comment by martindavid** [comment]
I was about to submit an issue. It's annoying to get the notification about `Invalid API Key`

**Comment by ayoisaiah** [comment]
I'm also having this `Invalid API Key` issue

**Comment by yujinyuz** [comment]
Me, too! Will have to disable wakatime in the meantime. Invalid API key error is quite annoying

**Comment by yriveiro** [comment]
@martindavid annoying is too nice 😄, I will need to disable the plugin until a fix be released.

I found this on my wakatime log:

```json
{"now": "2020/07/27 12:12:55 +0100", 
"version": "13.0.5", 
"plugin": 
"vim/800 vim-wakatime/8.0.0", 
"time": 1595848345.0, 
"caller": "/Users/yriveiro/.config/nvim/plugged/vim-wakatime/packages/wakatime/api.py",
 "lineno": 327, 
"file": "/Users/yriveiro/Development/backend/app/app/NERD_tree_1",
 "level": "WARNING", 
"message": "{'response_code': 401, 'response_content': '{\"error\":\"Unauthorized\"}\\n'}"}
```

**Comment by airtonzanon** [comment]
Having the same issue here as well.

**Comment by heraldofsolace** [comment]
Having the same issue

**Comment by alanhamlett** [comment]
Sorry, this was me. 😭 I broke the api key parsing, but it's fixed now. The plugin saves your stats and syncs them up the next time the plugin runs (the next time you're typing) so nothing is lost, but still sorry about the frustration it may have caused.

**Comment by jacobmischka** [comment]
Thanks for the quick fix!
