### ISSUE TITLE
Improve Startup Time

### ISSUE THREAD

**Issue by smolck** [wakatime/vim-wakatime#88]
In a bit of a recent quest to improve my Neovim startup time, I've found via [vim-startup](https://github.com/dstein64/vim-startuptime) that this plugin takes ~90ms to load on startup, which is about 42% of my total startup time. I'm not really sure where the slow startup is coming from, but it would be great if that could be improved.

If you need more information about my setup or such, feel free to let me know.

**Comment by alanhamlett** [comment]
Some things you could do to narrow down the source of slowness:

1. Comment out the autocommand events section (disabling event listeners) so the plugin stops tracking time on startup. This shows if the slowness comes from tracking time too early when starting up.
https://github.com/wakatime/vim-wakatime/blob/dd74c71cd2ea23b4a6cba4b05c873983c16e297c/plugin/wakatime.vim#L611

2. Comment out the plugin init call. This shows if the slowness comes from reading the `~/.wakatime.cfg` file to load settings when starting up. https://github.com/wakatime/vim-wakatime/blob/dd74c71cd2ea23b4a6cba4b05c873983c16e297c/plugin/wakatime.vim#L608

You should do each one individually, restarting Neovim each time to see if disabling one improves startup time.

**Comment by gandarez** [comment]
Does that problem is solved?

**Comment by smolck** [comment]
Yeah, doesn't seem to be an issue for me any longer, wakatime.vim sources in ~5 seconds now. Could've been a config-specific thing (my config has changed since making this issue), or something else, I don't know, but I have no issue with the startup time now.

I'll go ahead and close this.
