### ISSUE TITLE
Update page: https://wakatime.com/vim, some installation forms are missing

### ISSUE THREAD

**Issue by danitw** [wakatime/vim-wakatime#89]

**Comment by alanhamlett** [comment]
Added vim-plug instructions. Any others you recommend?

**Comment by danitw** [comment]
i only use vim plug but also have the neobundle q on the vimawesome plugins website has this way of installing and here is no example: https://vimawesome.com/plugin/fugitive-vim

**Comment by alanhamlett** [comment]
Seems neobundle isn't an active project anymore https://github.com/Shougo/neobundle.vim
