### ISSUE TITLE
using list as a string error on wakatimetoday command

### ISSUE THREAD

**Issue by NikosEfthias** [wakatime/vim-wakatime#97]
![image](https://user-images.githubusercontent.com/9097437/132691785-f771cf23-3cd8-4113-a01e-2329f3e3677a.png)

I am using neovim this just started happening yesterday out of nowhere

**Comment by alanhamlett** [comment]
Fixed with 5ef2cc4c68af5d291ba85dc444ebb1b26158444c. Please update your vim-wakatime plugin to get the fix.
